<definitions
    
     targetNamespace="http://www.reuters.com/ns/2007/09/01/GCAP/CS/PM/PriceUpdateRequestFormatter"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.reuters.com/ns/2007/09/01/GCAP/CS/PM/PriceUpdateRequestFormatter"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <import namespace="http://www.reuters.com/ns/2007/09/01/GCAP/CS/PM/PriceUpdateRequestFormatter"
         location="http://eaidev2:8004/TransformPriceUpdateToCSFormat/PriceUpdateRequest?WSDL"/>
    <plnk:partnerLinkType name="TransformPriceUpdateRequest_PL">
        <plnk:role name="TransformPriceUpdateRequest_Role">
            <plnk:portType name="tns:TransformPriceUpdateRequest"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
