<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CS.PM.212_CSPriceUpdateRequest.xsd"/>
      <rootElement name="priceUpdateRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/PriceUpdate"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.CS.PM.213_ExtendedCSPriceUpdateRequest.xsd"/>
      <rootElement name="priceUpdateRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/ExtendedPriceUpdateRequest"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [TUE JUN 29 12:38:48 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/ExtendedPriceUpdateRequest" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:gcap-cps="http://www.reuters.com/ns/2007/09/01/GCAP/CommonPriceStructures" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonNillablePriceTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gcap-cpt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonPriceTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:xsdLocal="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/PriceUpdate" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl gcap-cmt gcap-cps xsd ns1 gcap-cpt xsdLocal ns2 ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns0:priceUpdateRequest>
      <ns0:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </ns0:eaiHeader>
      <ns0:logicalCountry>
        <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/CountryCodeCoreSuiteInstanceMap.dvm&quot;,&quot;SiebelCountry&quot;,/xsdLocal:priceUpdateRequest/xsdLocal:logicalCountry,&quot;CSInstance&quot;,&quot;&quot;)"/>
      </ns0:logicalCountry>
      <ns0:messageHeader>
        <gcap-cmt:messageId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:messageCode>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageCode"/>
        </gcap-cmt:messageCode>
        <gcap-cmt:version>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:version"/>
        </gcap-cmt:version>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:userId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:userId"/>
        </gcap-cmt:userId>
        <gcap-cmt:objectSystem>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:objectSystem"/>
        </gcap-cmt:objectSystem>
      </ns0:messageHeader>
      <ns0:priceUpdateReqHeader>
        <gcap-cps:CSInstance>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqHeader/gcap-cps:CSInstance"/>
        </gcap-cps:CSInstance>
        <gcap-cps:priceListNumber>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqHeader/gcap-cps:priceListNumber"/>
        </gcap-cps:priceListNumber>
      </ns0:priceUpdateReqHeader>
      <ns0:index>
        <xsl:value-of select="string(&quot;&quot;)"/>
      </ns0:index>
      <xsl:for-each select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqLineItem">
        <ns0:priceUpdateReqLineItem>
          <gcap-cps:PLI>
            <xsl:value-of select="gcap-cps:PLI"/>
          </gcap-cps:PLI>
          <gcap-cps:startDate>
            <xsl:value-of select="gcap-cps:startDate"/>
          </gcap-cps:startDate>
          <gcap-cps:value>
            <xsl:value-of select="gcap-cps:value"/>
          </gcap-cps:value>
          <gcap-cps:currency>
            <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/CountryISOCurCodeCSCurCode.dvm&quot;,&quot;CountryISOCurCode&quot;,concat(../xsdLocal:logicalCountry,gcap-cps:currency),&quot;CSCurrencyCode&quot;,gcap-cps:currency)"/>
          </gcap-cps:currency>
          <gcap-cps:comType>
            <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/SiebelRevenueNExchangeTypeCSComponentType.dvm&quot;,&quot;SiebelValue&quot;,gcap-cps:comType,&quot;CSValue&quot;,&quot; &quot;)"/>
          </gcap-cps:comType>
          <gcap-cps:pliId>
            <xsl:value-of select="gcap-cps:pliId"/>
          </gcap-cps:pliId>
        </ns0:priceUpdateReqLineItem>
      </xsl:for-each>
    </ns0:priceUpdateRequest>
  </xsl:template>
</xsl:stylesheet>
