<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CS.PM.213_ExtendedCSPriceUpdateRequest.xsd"/>
      <rootElement name="priceUpdateRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/ExtendedPriceUpdateRequest"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.CS.PM.206_PriceUpdateRequest.xsd"/>
      <rootElement name="CSPriceUpdate" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/PriceUpdate"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [TUE JUN 29 12:39:22 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:xsdLocal="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/ExtendedPriceUpdateRequest" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:gcap-cps="http://www.reuters.com/ns/2007/09/01/GCAP/CommonPriceStructures" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonNillablePriceTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gcap-cpt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonPriceTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/PM/PriceUpdate" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:gcap-sa="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl xsdLocal gcap-cmt gcap-cps xsd ns1 gcap-cpt gcap-sa ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns0:CSPriceUpdate>
      <ns0:eaiHeader>
        <ns0:applicationId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:applicationId"/>
        </ns0:applicationId>
        <ns0:transactionId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:transactionId"/>
        </ns0:transactionId>
        <ns0:messageId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:messageId"/>
        </ns0:messageId>
        <ns0:messageHistory>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:messageHistory"/>
        </ns0:messageHistory>
        <ns0:tracingId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:tracingId"/>
        </ns0:tracingId>
        <ns0:timeStamp>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </ns0:timeStamp>
        <ns0:instanceId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:instanceId"/>
        </ns0:instanceId>
        <ns0:timeToLive>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:timeToLive"/>
        </ns0:timeToLive>
        <ns0:payloadVersion>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:eaiHeader/gcap-cmt:payloadVersion"/>
        </ns0:payloadVersion>
      </ns0:eaiHeader>
      <ns0:country>
        <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:logicalCountry"/>
      </ns0:country>
      <ns0:messageHeader>
        <ns0:messageId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageId"/>
        </ns0:messageId>
        <ns0:transactionId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:transactionId"/>
        </ns0:transactionId>
        <ns0:messageHistory>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageHistory"/>
        </ns0:messageHistory>
        <ns0:tracingId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:tracingId"/>
        </ns0:tracingId>
        <ns0:messageCode>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:messageCode"/>
        </ns0:messageCode>
        <ns0:version>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:version"/>
        </ns0:version>
        <ns0:timeStamp>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:timeStamp"/>
        </ns0:timeStamp>
        <ns0:userId>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:userId"/>
        </ns0:userId>
        <ns0:objectSystem>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:messageHeader/gcap-cmt:objectSystem"/>
        </ns0:objectSystem>
      </ns0:messageHeader>
      <ns0:priceUpdateReqHeader>
        <ns0:priceListNumber>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqHeader/gcap-cps:priceListNumber"/>
        </ns0:priceListNumber>
        <ns0:CSInstance>
          <xsl:value-of select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqHeader/gcap-cps:CSInstance"/>
        </ns0:CSInstance>
      </ns0:priceUpdateReqHeader>
      <xsl:for-each select="/xsdLocal:priceUpdateRequest/xsdLocal:priceUpdateReqLineItem[position() >= ../xsdLocal:index * 400.0 + 1.0 and position() &lt;= ../xsdLocal:index + 1.0 * 400.0]">
        <ns0:priceUpdateReqLineItem>
          <ns0:PLI>
            <xsl:value-of select="gcap-cps:PLI"/>
          </ns0:PLI>
          <ns0:startDate>
            <xsl:value-of select="gcap-cps:startDate"/>
          </ns0:startDate>
          <ns0:value>
            <xsl:value-of select="gcap-cps:value"/>
          </ns0:value>
          <ns0:currency>
            <xsl:value-of select="gcap-cps:currency"/>
          </ns0:currency>
          <ns0:comType>
            <xsl:value-of select="gcap-cps:comType"/>
          </ns0:comType>
          <ns0:pliId>
            <xsl:value-of select="gcap-cps:pliId"/>
          </ns0:pliId>
        </ns0:priceUpdateReqLineItem>
      </xsl:for-each>
    </ns0:CSPriceUpdate>
  </xsl:template>
</xsl:stylesheet>
