<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.OM.225_OrderStatus.xsd"/>
      <rootElement name="crmOrderStatus" namespace="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement/CCRM"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="InboundCompassOrder.wsdl"/>
      <rootElement name="RCRMInboundCompassOrderOperation_Input" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/RCRM"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU OCT 30 21:20:35 GMT 2008]. -->
?>
<xsl:stylesheet version="1.0" xmlns:xsdLocal="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement/CCRM" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.reuters.com/ns/2007/09/01/GCAP/RCRM" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsdLocal1="http://www.siebel.com/xml/RCRM%20Order%20Entry" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl xsdLocal cmt xsd ns0 tns soap soapenc xsdLocal1 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <tns:RCRMInboundCompassOrderOperation_Input>
      <xsdLocal1:OrderRequest>
        <xsdLocal1:MessageId>
          <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:eaiHeader/cmt:applicationId"/>
        </xsdLocal1:MessageId>
        <xsdLocal1:OrderEntry-Orders>
          <xsdLocal1:OrderNumber>
            <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:orderHeader/xsdLocal:CRMOrderNumber"/>
          </xsdLocal1:OrderNumber>
          <xsdLocal1:RCRMLegacyOrderNumber>
            <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:orderHeader/xsdLocal:orderNumber"/>
          </xsdLocal1:RCRMLegacyOrderNumber>
          <xsl:for-each select="/xsdLocal:crmOrderStatus/xsdLocal:orderLineItem">
            <xsdLocal1:OrderEntry-LineItems>
              <xsl:choose>
                <xsl:when test="../xsdLocal:orderHeader/xsdLocal:entrepriseCode = &quot;0000&quot;">
                  <xsdLocal1:RCRMField1>
                    <xsl:value-of select="string(&quot;&quot;)"/>
                  </xsdLocal1:RCRMField1>
                </xsl:when>
                <xsl:otherwise>
                  <xsdLocal1:RCRMField1>
                    <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:entrepriseCode"/>
                  </xsdLocal1:RCRMField1>
                </xsl:otherwise>
              </xsl:choose>
              <xsdLocal1:RCRMProductLoginType>
                <xsl:value-of select="xsdLocal:userIDtype"/>
              </xsdLocal1:RCRMProductLoginType>
              <xsdLocal1:RCRMFulfilmentStatus>
                <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/OrderPermissioningStatus.dvm&quot;,&quot;EAIPermissioningStatus&quot;,xsdLocal:orderPermissionStatus,&quot;SiebelPermissioningStatus&quot;,xsdLocal:orderPermissionStatus)"/>
              </xsdLocal1:RCRMFulfilmentStatus>
              <xsl:choose>
                <xsl:when test="xsdLocal:SID = &quot;00000&quot;">
                  <xsdLocal1:RCRMSID>
                    <xsl:value-of select="string(&quot;&quot;)"/>
                  </xsdLocal1:RCRMSID>
                </xsl:when>
                <xsl:otherwise>
                  <xsdLocal1:RCRMSID>
                    <xsl:value-of select="xsdLocal:SID"/>
                  </xsdLocal1:RCRMSID>
                </xsl:otherwise>
              </xsl:choose>
              <xsdLocal1:RootId>
                <xsl:value-of select="xsdLocal:rootItemId"/>
              </xsdLocal1:RootId>
              <xsdLocal1:RCRMContactUserNumber>
                <xsl:value-of select="xsdLocal:userNumber"/>
              </xsdLocal1:RCRMContactUserNumber>
              <xsdLocal1:RCRMILA>
                <xsl:value-of select="xsdLocal:ILA"/>
              </xsdLocal1:RCRMILA>
              <xsdLocal1:RCRMErrorMessage>
                <xsl:value-of select="xsdLocal:requestStatus"/>
              </xsdLocal1:RCRMErrorMessage>
              <xsl:choose>
                <xsl:when test="(xsdLocal:userIDtype = &quot;QUID&quot;) and (xsdLocal:QUID != &quot;00000&quot;)">
                  <xsdLocal1:RCRMContactUserId>
                    <xsl:value-of select="xsdLocal:QUID"/>
                  </xsdLocal1:RCRMContactUserId>
                </xsl:when>
                <xsl:otherwise>
                  <xsdLocal1:RCRMContactUserId>
                    <xsl:value-of select="xsdLocal:userId"/>
                  </xsdLocal1:RCRMContactUserId>
                </xsl:otherwise>
              </xsl:choose>
                <xsdLocal1:Status>
                <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/OrderLineStatus.dvm&quot;,&quot;EAIOrderLineStatus&quot;,xsdLocal:orderLinestatus,&quot;SiebelOrderLineStatus&quot;,xsdLocal:orderLinestatus)"/>
              </xsdLocal1:Status>
              <xsdLocal1:Id>
                <xsl:value-of select="xsdLocal:CRMOLIId"/>
              </xsdLocal1:Id>
              <xsdLocal1:RCRMCompassItemNumber>
                <xsl:value-of select="xsdLocal:itemNumber"/>
              </xsdLocal1:RCRMCompassItemNumber>
              <xsdLocal1:AssetIntegrationId>
                <xsl:value-of select="xsdLocal:assetIntegrationId"/>
              </xsdLocal1:AssetIntegrationId>
            </xsdLocal1:OrderEntry-LineItems>
          </xsl:for-each>
        </xsdLocal1:OrderEntry-Orders>
        <xsdLocal1:ActionCode>
          <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:messageHeader/xsdLocal:actionCode"/>
        </xsdLocal1:ActionCode>
        <xsdLocal1:MessageHistory>
          <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:eaiHeader/cmt:messageHistory"/>
        </xsdLocal1:MessageHistory>
        <xsdLocal1:UserId>
          <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:messageHeader/xsdLocal:userId"/>
        </xsdLocal1:UserId>
        <xsdLocal1:SourceSystem>
          <xsl:value-of select="/xsdLocal:crmOrderStatus/xsdLocal:eaiHeader/cmt:applicationId"/>
        </xsdLocal1:SourceSystem>
      </xsdLocal1:OrderRequest>
    </tns:RCRMInboundCompassOrderOperation_Input>
  </xsl:template>
</xsl:stylesheet>
