<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CS.UOM.276_UserOrderRequest.xsd"/>
      <rootElement name="CSUserOrderRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/UOM/UserOrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://ukcq-eai05:7777/TransformToCSUserRequest/TransformToCSUserRequest?wsdl"/>
      <rootElement name="CSUserOrder" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/UOM/UserOrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [MON JUN 22 19:46:35 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:gcap-cuot="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserOrderTypes" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CS/UOM/UserOrderManagement" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gcap-nuot="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserOrderTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl gcap-cmt xsd gcap-cuot local gcap-nuot ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <local:CSUserOrder>
      <local:eaiHeader>
        <local:applicationId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:applicationId"/>
        </local:applicationId>
        <local:transactionId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:transactionId"/>
        </local:transactionId>
        <local:messageId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:messageId"/>
        </local:messageId>
        <local:messageHistory>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:messageHistory"/>
        </local:messageHistory>
        <local:tracingId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:tracingId"/>
        </local:tracingId>
        <local:timeStamp>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:timeStamp"/>
        </local:timeStamp>
        <local:instanceId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:instanceId"/>
        </local:instanceId>
        <local:timeToLive>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:timeToLive"/>
        </local:timeToLive>
        <local:payloadVersion>
          <xsl:value-of select="/local:CSUserOrderRequest/local:eaiHeader/gcap-cmt:payloadVersion"/>
        </local:payloadVersion>
      </local:eaiHeader>
      <local:messageHeader>
        <local:logicalCountry>
          <xsl:value-of select="/local:CSUserOrderRequest/local:country"/>
        </local:logicalCountry>
        <local:messageId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:messageId"/>
        </local:messageId>
        <local:transactionId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:transactionId"/>
        </local:transactionId>
        <local:messageHistory>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:messageHistory"/>
        </local:messageHistory>
        <local:tracingId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:tracingId"/>
        </local:tracingId>
        <xsl:choose>
          <xsl:when test="(/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode = &quot;CREATE&quot;) and (/local:CSUserOrderRequest/local:userOrderHeader/local:siebelOrderNumber != &quot;&quot;)">
            <local:actionCode>
              <xsl:value-of select="string(&quot;OM80&quot;)"/>
            </local:actionCode>
          </xsl:when>
          <xsl:otherwise>
            <local:actionCode>
              <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/ATHCS_OrderActionCodeMap.dvm&quot;,&quot;AthenaActionCode&quot;,/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode,&quot;CSActionCode&quot;,substring(/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode,1.0,4.0))"/>
            </local:actionCode>
          </xsl:otherwise>
        </xsl:choose>
        <local:version>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:version"/>
        </local:version>
        <local:timeStamp>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:timeStamp"/>
        </local:timeStamp>
        <local:userId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:userId"/>
        </local:userId>
        <local:objectSystem>
          <xsl:value-of select="/local:CSUserOrderRequest/local:messageHeader/gcap-cmt:objectSystem"/>
        </local:objectSystem>
        <local:sourceSystem>
          <xsl:value-of select="/local:CSUserOrderRequest/local:sourceSystem"/>
        </local:sourceSystem>
      </local:messageHeader>
      <local:userOrderHeader>
        <local:transactionId>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:transactionId"/>
        </local:transactionId>
        <local:sourceSystem>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:sourceSystem"/>
        </local:sourceSystem>
        <local:subscriber>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:subscriber"/>
        </local:subscriber>
        <local:subAccount>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:subAccount"/>
        </local:subAccount>
        <local:effectiveDate>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:effectiveDate"/>
        </local:effectiveDate>
        <local:siebelOrderNumber>
          <xsl:value-of select="/local:CSUserOrderRequest/local:userOrderHeader/local:siebelOrderNumber"/>
        </local:siebelOrderNumber>
        <xsl:choose>
          <xsl:when test="(/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode = &quot;CREATE&quot;) and (/local:CSUserOrderRequest/local:userOrderHeader/local:siebelOrderNumber != &quot;&quot;)">
            <local:actionCode>
              <xsl:value-of select="string(&quot;OM80&quot;)"/>
            </local:actionCode>
          </xsl:when>
          <xsl:otherwise>
            <local:actionCode>
              <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/ATHCS_OrderActionCodeMap.dvm&quot;,&quot;AthenaActionCode&quot;,/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode,&quot;CSActionCode&quot;,substring(/local:CSUserOrderRequest/local:userOrderHeader/local:actionCode,1.0,4.0))"/>
            </local:actionCode>
          </xsl:otherwise>
        </xsl:choose>
      </local:userOrderHeader>
      <xsl:for-each select="/local:CSUserOrderRequest/local:userOrderLineItem">
        <local:userOrderLineItem>
          <local:uniqueUserLineId>
            <xsl:value-of select="local:UOLIId"/>
          </local:uniqueUserLineId>
          <local:athenSubId>
            <xsl:value-of select="local:athenaSubId"/>
          </local:athenSubId>
          <local:firstName>
            <xsl:value-of select="local:firstName"/>
          </local:firstName>
          <local:lastName>
            <xsl:value-of select="local:lastName"/>
          </local:lastName>
          <local:TSAID>
            <xsl:value-of select="local:TSAID"/>
          </local:TSAID>
          <local:emailId>
            <xsl:value-of select="local:emailId"/>
          </local:emailId>
          <local:AKR>
            <xsl:value-of select="local:AKR"/>
          </local:AKR>
          <local:PLI>
            <xsl:value-of select="local:PLI"/>
          </local:PLI>
          <local:installRemoveInd>
            <xsl:value-of select="local:installRemoveInd"/>
          </local:installRemoveInd>
          <local:itemNumber>
            <xsl:value-of select="local:itemNumber"/>
          </local:itemNumber>
          <local:hardStopFlag>
            <xsl:value-of select="local:hardStopFlag"/>
          </local:hardStopFlag>
        </local:userOrderLineItem>
      </xsl:for-each>
    </local:CSUserOrder>
  </xsl:template>
</xsl:stylesheet>
