<?binding.jca CPFGAM_POLLING_V_db.jca?>
<definitions name="CPFGAM_POLLING_V" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CPFGAM_POLLING_V/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CPFGAM_POLLING_V/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CPFGAMPOLLINGV">
    <plt:partnerLinkType name="CPFGAM_POLLING_V_plt">
        <plt:role name="CPFGAM_POLLING_V_role">
            <plt:portType name="tns:CPFGAM_POLLING_V_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CPFGAMPOLLINGV" schemaLocation="CPFGAMPOLLINGV_table.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.reuters.com/ns/2007/09/01/GCAP/CPFG/AccountPublish" schemaLocation="EAI.MSG.CPFG.AM.225_StandalonePublishAccountEventRequest.xsd"/>
        </xsd:schema>
    </types>
    <message name="CpfgamPollingVCollection_msg">
        <part name="CpfgamPollingVCollection" element="top:CpfgamPollingVCollection"/>
    </message>
    <portType name="CPFGAM_POLLING_V_ptt">
        <operation name="receive">
            <input message="tns:CpfgamPollingVCollection_msg"/>
        </operation>
    </portType>
</definitions>
