<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="submitUserOrderRequestInRS"
     targetNamespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/ATH/UOM/SubmitUserOrderRequest"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/ATH/UOM/SubmitUserOrderRequest"
     xmlns:out1="http://xml.netbeans.org/schema/BillingNotifyMessage"
     xmlns:inp1="http://xml.netbeans.org/schema/BillingNotifyMessage"
    >
    <types>
     
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xml.netbeans.org/schema/BillingNotifyMessage" schemaLocation="EAI.MSG.ATH.UOM.274_UserOrderRequest.xsd" />
      </schema>
    </types>
    <message name="billingInfoRequest_request">
        <part name="billingInfoRequest" element="out1:billingInfoRequest"/>
    </message>
    <message name="billingInfoResponse_reply">
        <part name="billingInfoResponse" element="out1:billingInfoResponse"/>
    </message>
    <portType name="submitUserOrderRequest_ppt">
        <operation name="submitUserOrderRequest">
            <input message="tns:billingInfoRequest_request"/>
            <output message="tns:billingInfoResponse_reply"/>
        </operation>
    </portType>
</definitions>
