<?binding.jca UpdateOrderCache_db.jca?>
<definitions name="UpdateOrderCache" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateOrderCache/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/UpdateOrderCache/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderCache">
    <plt:partnerLinkType name="UpdateOrderCache_plt">
        <plt:role name="UpdateOrderCache_role">
            <plt:portType name="tns:UpdateOrderCache_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderCache" schemaLocation="UpdateOrderCache_table.xsd"/>
        </schema>
    </types>
    <message name="OrderCacheCollection_msg">
        <part name="OrderCacheCollection" element="top:OrderCacheCollection"/>
    </message>
    <portType name="UpdateOrderCache_ptt">
        <operation name="update">
            <input message="tns:OrderCacheCollection_msg"/>
        </operation>
    </portType>
</definitions>
