<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.UTL.185_CheckSequenceRequest.xsd"/>
      <rootElement name="checkSequenceRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/UTL/Sequencer"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAIOWNER_MESSAGE_SEQUENCER_REGISTER_SEQ.xsd"/>
      <rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EAIOWNER/MESSAGE_SEQUENCER/REGISTER_SEQ/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI AUG 07 23:47:45 BST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EAIOWNER/MESSAGE_SEQUENCER/REGISTER_SEQ/" xmlns:xsdLocal="http://www.reuters.com/ns/2007/09/01/GCAP/UTL/Sequencer" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:gcap-sa="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl gcap-cmt xsdLocal xsd gcap-sa db bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <db:InputParameters>
      <db:P_CORRELATION_ID>
        <xsl:value-of select="/xsdLocal:checkSequenceRequest/xsdLocal:seqRequestDetails/xsdLocal:correlationID"/>
      </db:P_CORRELATION_ID>
      <db:P_CONTEXT_ID>
        <xsl:value-of select="orcl:right-trim(orcl:left-trim(/xsdLocal:checkSequenceRequest/xsdLocal:seqRequestDetails/xsdLocal:contextId))"/>
      </db:P_CONTEXT_ID>
      <db:P_CONTEXT>
        <xsl:value-of select="/xsdLocal:checkSequenceRequest/xsdLocal:seqRequestDetails/xsdLocal:context"/>
      </db:P_CONTEXT>
      <db:P_PROCESS>
        <xsl:text disable-output-escaping="no">AsyncSequenceChecker</xsl:text>
      </db:P_PROCESS>
      <db:P_MSG_TYPE>
        <xsl:value-of select="/xsdLocal:checkSequenceRequest/xsdLocal:seqRequestDetails/xsdLocal:messageType"/>
      </db:P_MSG_TYPE>
      <db:P_CHECKER_INST_ID>
        <xsl:value-of select="/xsdLocal:checkSequenceRequest/xsdLocal:eaiHeader/gcap-cmt:instanceId"/>
      </db:P_CHECKER_INST_ID>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>
