<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.TF.152_VettingRequest.xsd"/>
      <rootElement name="vettingRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/TechFul"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.TOM.TF.153_VettingRequest.xsd"/>
      <rootElement name="vettingRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/TOM/TechFul"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [TUE FEB 15 20:06:36 GMT+05:30 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns3="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserTypes" xmlns:xsdLocal="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/TechFul" xmlns:cqt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonQuoteTypes" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/TOM/TechFul" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:gcap-sa="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" exclude-result-prefixes="xsl cmt ns3 xsd ns2 xsdLocal cqt gcap-sa ns1 ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
 <ns0:vettingRequest>
      <ns0:eaiHeader>
        <cmt:applicationId>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:applicationId"/>
        </cmt:applicationId>
        <cmt:transactionId>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:transactionId"/>
        </cmt:transactionId>
        <cmt:messageId>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:messageId"/>
        </cmt:messageId>
        <cmt:messageHistory>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:messageHistory"/>
        </cmt:messageHistory>
        <cmt:tracingId>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:tracingId"/>
        </cmt:tracingId>
        <cmt:timeStamp>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </cmt:timeStamp>
        <cmt:instanceId>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:instanceId"/>
        </cmt:instanceId>
        <cmt:timeToLive>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:timeToLive"/>
        </cmt:timeToLive>
        <cmt:payloadVersion>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:eaiHeader/cmt:payloadVersion"/>
        </cmt:payloadVersion>
      </ns0:eaiHeader>
      <ns0:quoteHeader>
        <cqt:quoteNumber>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:quoteNumber"/>
        </cqt:quoteNumber>
        <cqt:revisionNumber>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:revisionNumber"/>
        </cqt:revisionNumber>
        <cqt:quoteHeaderName>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:quoteHeaderName"/>
        </cqt:quoteHeaderName>
        <cqt:orderType>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:orderType"/>
        </cqt:orderType>
        <cqt:createdBy>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:createdBy"/>
        </cqt:createdBy>
        <cqt:effectiveEndDate>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:effectiveEndDate"/>
        </cqt:effectiveEndDate>
        <cqt:locationID>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:locationID"/>
        </cqt:locationID>
        <cqt:customerRequiredDate>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:customerRequiredDate"/>
        </cqt:customerRequiredDate>
        <cqt:purchaseOrderNumber>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:purchaseOrderNumber"/>
        </cqt:purchaseOrderNumber>
        <cqt:quoteStatus>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:quoteStatus"/>
        </cqt:quoteStatus>
        <cqt:orderNumber>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:orderNumber"/>
        </cqt:orderNumber>
        <cqt:omsContactID>
          <xsl:value-of select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:assignedOMS"/>
        </cqt:omsContactID>
        <xsl:for-each select="/xsdLocal:vettingRequest/xsdLocal:quoteHeader/cqt:notes">
          <cqt:notes>
            <cqt:noteType>
              <xsl:value-of select="cqt:noteType"/>
            </cqt:noteType>
            <cqt:note>
              <xsl:value-of select="cqt:note"/>
            </cqt:note>
          </cqt:notes>
        </xsl:for-each>
      </ns0:quoteHeader>
      <xsl:for-each select="/xsdLocal:vettingRequest/xsdLocal:quoteLineItem">
        <ns0:orderLineItem>
          <cqt:priceListItem>
            <xsl:value-of select="cqt:partNumber"/>
          </cqt:priceListItem>
          <cqt:quantity>
            <xsl:value-of select="cqt:quantity"/>
          </cqt:quantity>
          <cqt:subscriberID>
            <xsl:value-of select="cqt:subscriberID"/>
          </cqt:subscriberID>
          <cqt:fulfilmentAccountId>
            <xsl:value-of select="cqt:fulfilmentAccountId"/>
          </cqt:fulfilmentAccountId>
          <cqt:productId>
            <xsl:value-of select="cqt:productIntegrationId"/>
          </cqt:productId>
          <cqt:assetIntegrationId>
            <xsl:value-of select="cqt:assetIntegrationID"/>
          </cqt:assetIntegrationId>
          <cqt:productLineId>
            <xsl:value-of select="cqt:lineID"/>
          </cqt:productLineId>
          <cqt:parentQuoteLineId>
            <xsl:value-of select="cqt:parentQuoteItemID"/>
          </cqt:parentQuoteLineId>
          <cqt:productBillingId>
            <xsl:value-of select="cqt:billingAccountId"/>
          </cqt:productBillingId>
          <cqt:action>
            <xsl:value-of select="cqt:actionCode"/>
          </cqt:action>
          <cqt:altBillingId>
            <xsl:value-of select="cqt:altInstallationAddBilAccId"/>
          </cqt:altBillingId>
          <cqt:productInstallDate>
            <xsl:value-of select="cqt:rcrmInstallDate"/>
          </cqt:productInstallDate>
          <cqt:freeTrialDuration>
            <xsl:value-of select="cqt:rcrmFreeTrialDuration"/>
          </cqt:freeTrialDuration>
          <cqt:productName>
            <xsl:value-of select="cqt:productName"/>
          </cqt:productName>
          <xsl:for-each select="cqt:attribute">
            <cqt:attribute>
              <cqt:attributeName>
                <xsl:value-of select="cqt:attributeName"/>
              </cqt:attributeName>
              <cqt:attributeValue>
                <xsl:value-of select="cqt:attributeValue"/>
              </cqt:attributeValue>
            </cqt:attribute>
          </xsl:for-each>
          <cqt:technicalApprovalRequired>
            <xsl:value-of select="cqt:technicalApprovalRequired"/>
          </cqt:technicalApprovalRequired>
          <cqt:technicalFulfilmentRequired>
            <xsl:value-of select="cqt:technicalFulfilmentRequired"/>
          </cqt:technicalFulfilmentRequired>
        </ns0:orderLineItem>
      </xsl:for-each>
    </ns0:vettingRequest>
  </xsl:template>
</xsl:stylesheet>
