// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.reuters.ns._2007._09._01.gcap.eai.cs.om.ordermanagement;


public class _CSCompassOLI implements java.io.Serializable {
    protected java.lang.String CRMOLIId;
    protected java.lang.String actionCode;
    protected java.lang.String salesCode;
    protected java.lang.String subAccount;
    protected java.lang.String PLI;
    protected java.lang.String AKR;
    protected java.lang.String userID;
    protected java.lang.String QUID;
    protected java.lang.String permissionDate;
    protected java.lang.String specialPrice;
    protected java.lang.String specialPriceCurr;
    protected java.lang.String specialPriceRestrictionDate;
    protected java.lang.String itemNumber;
    protected java.lang.String startStopBillingDate;
    protected java.lang.String billingType;
    protected java.lang.String billingNote;
    protected java.lang.String STB;
    protected java.lang.String permBillFlag;
    protected java.lang.String installToSubscriber;
    protected java.lang.String installToItemNumber;
    
    public _CSCompassOLI() {
    }
    
    public java.lang.String getCRMOLIId() {
        return CRMOLIId;
    }
    
    public void setCRMOLIId(java.lang.String CRMOLIId) {
        this.CRMOLIId = CRMOLIId;
    }
    
    public java.lang.String getActionCode() {
        return actionCode;
    }
    
    public void setActionCode(java.lang.String actionCode) {
        this.actionCode = actionCode;
    }
    
    public java.lang.String getSalesCode() {
        return salesCode;
    }
    
    public void setSalesCode(java.lang.String salesCode) {
        this.salesCode = salesCode;
    }
    
    public java.lang.String getSubAccount() {
        return subAccount;
    }
    
    public void setSubAccount(java.lang.String subAccount) {
        this.subAccount = subAccount;
    }
    
    public java.lang.String getPLI() {
        return PLI;
    }
    
    public void setPLI(java.lang.String PLI) {
        this.PLI = PLI;
    }
    
    public java.lang.String getAKR() {
        return AKR;
    }
    
    public void setAKR(java.lang.String AKR) {
        this.AKR = AKR;
    }
    
    public java.lang.String getUserID() {
        return userID;
    }
    
    public void setUserID(java.lang.String userID) {
        this.userID = userID;
    }
    
    public java.lang.String getQUID() {
        return QUID;
    }
    
    public void setQUID(java.lang.String QUID) {
        this.QUID = QUID;
    }
    
    public java.lang.String getPermissionDate() {
        return permissionDate;
    }
    
    public void setPermissionDate(java.lang.String permissionDate) {
        this.permissionDate = permissionDate;
    }
    
    public java.lang.String getSpecialPrice() {
        return specialPrice;
    }
    
    public void setSpecialPrice(java.lang.String specialPrice) {
        this.specialPrice = specialPrice;
    }
    
    public java.lang.String getSpecialPriceCurr() {
        return specialPriceCurr;
    }
    
    public void setSpecialPriceCurr(java.lang.String specialPriceCurr) {
        this.specialPriceCurr = specialPriceCurr;
    }
    
    public java.lang.String getSpecialPriceRestrictionDate() {
        return specialPriceRestrictionDate;
    }
    
    public void setSpecialPriceRestrictionDate(java.lang.String specialPriceRestrictionDate) {
        this.specialPriceRestrictionDate = specialPriceRestrictionDate;
    }
    
    public java.lang.String getItemNumber() {
        return itemNumber;
    }
    
    public void setItemNumber(java.lang.String itemNumber) {
        this.itemNumber = itemNumber;
    }
    
    public java.lang.String getStartStopBillingDate() {
        return startStopBillingDate;
    }
    
    public void setStartStopBillingDate(java.lang.String startStopBillingDate) {
        this.startStopBillingDate = startStopBillingDate;
    }
    
    public java.lang.String getBillingType() {
        return billingType;
    }
    
    public void setBillingType(java.lang.String billingType) {
        this.billingType = billingType;
    }
    
    public java.lang.String getBillingNote() {
        return billingNote;
    }
    
    public void setBillingNote(java.lang.String billingNote) {
        this.billingNote = billingNote;
    }
    
    public java.lang.String getSTB() {
        return STB;
    }
    
    public void setSTB(java.lang.String STB) {
        this.STB = STB;
    }
    
    public java.lang.String getPermBillFlag() {
        return permBillFlag;
    }
    
    public void setPermBillFlag(java.lang.String permBillFlag) {
        this.permBillFlag = permBillFlag;
    }
    public java.lang.String getInstallToSubscriber() {
        return installToSubscriber;
    }
    
    public void setInstallToSubscriber(java.lang.String installToSubscriber) {
        this.installToSubscriber = installToSubscriber;
    }
    
    public java.lang.String getInstallToItemNumber() {
        return installToItemNumber;
    }
    
    public void setInstallToItemNumber(java.lang.String installToItemNumber) {
        this.installToItemNumber = installToItemNumber;
    }
    
    public String[] getOrderLineValues() {
        String orderLineValues[] = 
        { CRMOLIId, actionCode, salesCode, subAccount, 
          PLI, AKR, userID, QUID, permissionDate, 
          specialPrice, specialPriceCurr, specialPriceRestrictionDate, 
          itemNumber, startStopBillingDate, billingType.toString(), 
          billingNote, STB.toString(),permBillFlag,installToSubscriber,installToItemNumber };
        return orderLineValues;
    }   
}
