<?binding.jca CPFGEF_POLLING_V_db.jca?>
<definitions name="CPFGEF_POLLING_V" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CPFGEF_POLLING_V/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CPFGEF_POLLING_V/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CPFGEFPOLLINGV">
<import namespace="http://schemas.oracle.com/bpel/extension" location="oramds:/soa/shared/bpel/RuntimeFault.wsdl"/>    
	<plt:partnerLinkType name="CPFGEF_POLLING_V_plt">
        <plt:role name="CPFGEF_POLLING_V_role">
            <plt:portType name="tns:CPFGEF_POLLING_V_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CPFGEFPOLLINGV" schemaLocation="CPFGEFPOLLINGV_table.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CPFG/ElectronicFulfilmentServices" schemaLocation="EAI.MSG.CPFG.EF.219_StandaloneElectronicFulfilmentRequest.xsd"/>
        </schema>
    </types>
    <message name="CpfgefPollingVCollection_msg">
        <part name="CpfgefPollingVCollection" element="top:CpfgefPollingVCollection"/>
    </message>
    <portType name="CPFGEF_POLLING_V_ptt">
        <operation name="receive">
            <input message="tns:CpfgefPollingVCollection_msg"/>
        </operation>
    </portType>
</definitions>
