<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.OM.125_OrderRequest.xsd"/>
      <rootElement name="orderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://eaidev2:7777/OrderFulfilmentCrossRefService/CrossRefServiceSplitOrderSOAPPort?WSDL"/>
      <rootElement name="splitOrderRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CPFG/OrderFulfilmentCrossRefService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [MON DEC 07 16:37:12 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CPFG/OrderFulfilmentCrossRefService" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:soap11-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsdLocal="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/OrderManagement" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:util="http://www.oracle.com/XSL/Transform/java/com.reuters.eai.util.StringHasher" exclude-result-prefixes="xsl cmt xsd xsdLocal ns0 mime wsdl soap12 tns soap soap11-enc xsi bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <tns:splitOrderRequest>
      <tns:eaiHeader>
        <tns:applicationId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:applicationId"/>
        </tns:applicationId>
        <tns:transactionId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:transactionId"/>
        </tns:transactionId>
        <tns:messageId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:messageId"/>
        </tns:messageId>
        <tns:messageHistory>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:messageHistory"/>
        </tns:messageHistory>
        <tns:tracingId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:tracingId"/>
        </tns:tracingId>
        <tns:timeStamp>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:timeStamp"/>
        </tns:timeStamp>
        <tns:instanceId>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:instanceId"/>
        </tns:instanceId>
        <tns:timeToLive>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:timeToLive"/>
        </tns:timeToLive>
        <tns:payloadVersion>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:eaiHeader/cmt:payloadVersion"/>
        </tns:payloadVersion>
      </tns:eaiHeader>
      <tns:crmOrder>
        <tns:logicalCountry>
          <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:logicalCountry"/>
        </tns:logicalCountry>
        <tns:orderHeader>
          <tns:CRMOrderNumber>
            <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/xsdLocal:CRMOrderNumber"/>
          </tns:CRMOrderNumber>
          <tns:installDate>
            <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/xsdLocal:installDate"/>
          </tns:installDate>
          <tns:removalDate>
            <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/xsdLocal:removalDate"/>
          </tns:removalDate>
          <tns:orderNote>
            <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/xsdLocal:orderNote"/>
          </tns:orderNote>
          <tns:orderStatus>
            <xsl:value-of select="/xsdLocal:orderRequest/xsdLocal:orderHeader/xsdLocal:orderStatus"/>
          </tns:orderStatus>
        </tns:orderHeader>
        <xsl:for-each select="/xsdLocal:orderRequest/xsdLocal:orderLineItem">
          <xsl:if test="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/PermissioningSystems.dvm&quot;,&quot;ABBREVIATION&quot;,xsdLocal:permissioningSystem,&quot;SYSTEM&quot;,xsdLocal:permissioningSystem) = &quot;COMMON_PLATFORM_FOR_GROWTH&quot;">
            <tns:orderLineItem>
              <tns:CRMOLIId>
                <xsl:value-of select="xsdLocal:CRMOLIId"/>
              </tns:CRMOLIId>
              <tns:parentOrderItemId>
                <xsl:value-of select="xsdLocal:parentOrderItemId"/>
              </tns:parentOrderItemId>
              <tns:rootItemId>
                <xsl:value-of select="xsdLocal:rootItemId"/>
              </tns:rootItemId>
              <tns:actionCode>
                <xsl:value-of select="xsdLocal:actionCode"/>
              </tns:actionCode>
              <tns:businessCase>
                <xsl:value-of select="xsdLocal:businessCase"/>
              </tns:businessCase>
              <tns:salesCode>
                <xsl:value-of select="xsdLocal:salesCode"/>
              </tns:salesCode>
              <tns:subscriber>
                <xsl:value-of select="xsdLocal:subscriber"/>
              </tns:subscriber>
              <tns:subAccount>
                <xsl:value-of select="xsdLocal:subAccount"/>
              </tns:subAccount>
              <tns:PLI>
                <xsl:value-of select="xsdLocal:PLI"/>
              </tns:PLI>
              <tns:permissioningSystem>
                <xsl:value-of select="xsdLocal:permissioningSystem"/>
              </tns:permissioningSystem>
              <tns:manualPermissioningRequired>
                <xsl:value-of select="xsdLocal:manualPermissioningRequired"/>
              </tns:manualPermissioningRequired>
              <tns:AKR>
                <xsl:value-of select="xsdLocal:AKR"/>
              </tns:AKR>
              <tns:userID>
                <xsl:value-of select="xsdLocal:userID"/>
              </tns:userID>
              <tns:userIDtype>
                <xsl:value-of select="xsdLocal:userIDtype"/>
              </tns:userIDtype>
              <tns:userNumber>
                <xsl:value-of select="xsdLocal:userNumber"/>
              </tns:userNumber>
              <tns:firstName>
                <xsl:value-of select="xsdLocal:firstName"/>
              </tns:firstName>
              <tns:lastname>
                <xsl:value-of select="xsdLocal:lastname"/>
              </tns:lastname>
              <tns:dob>
                <xsl:value-of select="xsdLocal:dob"/>
              </tns:dob>
              <tns:isNewUser>
                <xsl:value-of select="xsdLocal:isNewUser"/>
              </tns:isNewUser>
              <tns:installDate>
                <xsl:value-of select="xsdLocal:installDate"/>
              </tns:installDate>
              <tns:removalDate>
                <xsl:value-of select="xsdLocal:removalDate"/>
              </tns:removalDate>
              <tns:QUID>
                <xsl:value-of select="xsdLocal:QUID"/>
              </tns:QUID>
              <tns:discount>
                <xsl:value-of select="xsdLocal:discount"/>
              </tns:discount>
              <tns:specialPrice>
                <xsl:value-of select="xsdLocal:specialPrice"/>
              </tns:specialPrice>
              <tns:specialPriceCurr>
                <xsl:value-of select="xsdLocal:specialPriceCurr"/>
              </tns:specialPriceCurr>
              <tns:specialPriceRestrictionDate>
                <xsl:value-of select="xsdLocal:specialPriceRestrictionDate"/>
              </tns:specialPriceRestrictionDate>
              <tns:itemNumber>
                <xsl:value-of select="xsdLocal:itemNumber"/>
              </tns:itemNumber>
              <tns:startStopBillingDate>
                <xsl:value-of select="xsdLocal:startStopBillingDate"/>
              </tns:startStopBillingDate>
              <tns:billingType>
                <xsl:value-of select="xsdLocal:billingType"/>
              </tns:billingType>
              <tns:billingNote>
                <xsl:value-of select="xsdLocal:billingNote"/>
              </tns:billingNote>
              <tns:freeTrailFlag>
                <xsl:value-of select="xsdLocal:freeTrailFlag"/>
              </tns:freeTrailFlag>
              <tns:STB>
                <xsl:value-of select="xsdLocal:STB"/>
              </tns:STB>
              <tns:assetIntegrationId>
                <xsl:value-of select="xsdLocal:assetIntegrationId"/>
              </tns:assetIntegrationId>
              <tns:orderLineStatus>
                <xsl:value-of select="xsdLocal:orderLineStatus"/>
              </tns:orderLineStatus>
              <tns:permissioningStatus>
                <xsl:value-of select="xsdLocal:permissioningStatus"/>
              </tns:permissioningStatus>
              <tns:interfaceForBilling>
                <xsl:value-of select="xsdLocal:interfaceForBilling"/>
              </tns:interfaceForBilling>
              <tns:interfaceForFulfilment>
                <xsl:value-of select="xsdLocal:interfaceForFulfilment"/>
              </tns:interfaceForFulfilment>
              <tns:productIntegrationId>
                <xsl:value-of select="xsdLocal:productIntegrationId"/>
              </tns:productIntegrationId>
              <tns:freeTrialEndDate>
                <xsl:value-of select="xsdLocal:freeTrialEndDate"/>
              </tns:freeTrialEndDate>
              <xsl:for-each select="xsdLocal:configuredAttribute">
                <tns:configuredAttribute>
                  <tns:attributeIntegrationId>
                    <xsl:value-of select="xsdLocal:attributeIntegrationId"/>
                  </tns:attributeIntegrationId>
                  <tns:attributeName>
                    <xsl:value-of select="xsdLocal:attributeName"/>
                  </tns:attributeName>
                  <tns:valueIntegrationId>
                    <xsl:value-of select="substring(util:hashString(string(xsdLocal:value)),1,15)"/>
                  </tns:valueIntegrationId>
                  <tns:value>
                    <xsl:value-of select="xsdLocal:value"/>
                  </tns:value>
                </tns:configuredAttribute>
              </xsl:for-each>
            </tns:orderLineItem>
          </xsl:if>
        </xsl:for-each>
      </tns:crmOrder>
    </tns:splitOrderRequest>
  </xsl:template>
</xsl:stylesheet>
