<?xml version= '1.0' encoding= 'UTF-8' ?>
<definitions
     name="QuerySRDetails"
     targetNamespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/CSZ"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/CSZ"
     xmlns:out1="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/ServiceRequest"
     xmlns:inp1="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/ServiceRequest"
    >
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/ServiceRequest" schemaLocation="EAI.MSG.EAI.CSZ.246_EAICSZServiceRequest.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/ServiceRequest" schemaLocation="EAI.MSG.EAI.CSZ.247_EAICSZServiceResponse.xsd" />
      </schema>
    </types>
    <message name="EAICSZServiceRequest_request">
        <part name="EAICSZServiceRequest" element="out1:EAICSZServiceRequest"/>
    </message>
    <message name="EAICSZServiceResponse_reply">
        <part name="EAICSZServiceResponse" element="out1:EAICSZServiceResponse"/>
    </message>
    <portType name="getSRDetails_ppt">
        <operation name="getSRDetails">
            <input message="tns:EAICSZServiceRequest_request"/>
            <output message="tns:EAICSZServiceResponse_reply"/>
        </operation>
    </portType>
</definitions>
