<?binding.jca WriteOpportunity_db.jca?>
<definitions name="WriteOpportunity" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WriteOpportunity/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WriteOpportunity/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/WriteOpportunity">
    <plt:partnerLinkType name="WriteOpportunity_plt">
        <plt:role name="WriteOpportunity_role">
            <plt:portType name="tns:WriteOpportunity_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/WriteOpportunity" schemaLocation="WriteOpportunity_table.xsd"/>
        </schema>
    </types>
    <message name="InterfaceBufferCollection_msg">
        <part name="InterfaceBufferCollection" element="top:InterfaceBufferCollection"/>
    </message>
    <portType name="WriteOpportunity_ptt">
        <operation name="insert">
            <input message="tns:InterfaceBufferCollection_msg"/>
        </operation>
    </portType>
</definitions>
