<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.TOM.OM.239_UpdateOrderResponse.xsd"/>
      <rootElement name="orderResponseStatus" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/TOM/OM/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.TOM.OM.239_UpdateOrderResponse.xsd"/>
      <rootElement name="orderResponseStatus" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/TOM/OM/OrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [TUE JUN 30 12:41:06 GMT+05:30 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:comt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonOrderTypes" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:xsdLocal="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/TOM/OM/OrderManagement" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" exclude-result-prefixes="xsl cmt ns2 xsd comt ns0 xsdLocal ns1 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <xsdLocal:orderResponseStatus>
      <xsdLocal:eaiHeader>
        <cmt:applicationId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:applicationId"/>
        </cmt:applicationId>
        <cmt:transactionId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:transactionId"/>
        </cmt:transactionId>
        <cmt:messageId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:messageId"/>
        </cmt:messageId>
        <cmt:messageHistory>
          <xsl:value-of select="concat(/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:messageHistory,&quot;;EAI;&quot;)"/>
        </cmt:messageHistory>
        <cmt:tracingId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:tracingId"/>
        </cmt:tracingId>
        <cmt:timeStamp>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:timeStamp"/>
        </cmt:timeStamp>
        <cmt:instanceId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:instanceId"/>
        </cmt:instanceId>
        <cmt:timeToLive>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:timeToLive"/>
        </cmt:timeToLive>
        <cmt:payloadVersion>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:eaiHeader/cmt:payloadVersion"/>
        </cmt:payloadVersion>
      </xsdLocal:eaiHeader>
      <xsdLocal:orderHeader>
        <comt:CRMOrderId>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:CRMOrderId"/>
        </comt:CRMOrderId>
        <comt:actualInstallationDate>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:actualInstallationDate"/>
        </comt:actualInstallationDate>
        <comt:plannedInstallationDate>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:plannedInstallationDate"/>
        </comt:plannedInstallationDate>
        <comt:technicalFulfilmentStatus>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:technicalFulfilmentStatus"/>
        </comt:technicalFulfilmentStatus>
        <comt:technicalFulfilmentStatusReason>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:technicalFulfilmentStatusReason"/>
        </comt:technicalFulfilmentStatusReason>
        <comt:firstName>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:firstName"/>
        </comt:firstName>
        <comt:lastname>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:lastname"/>
        </comt:lastname>
        <comt:email>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:email"/>
        </comt:email>
        <comt:phone>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:phone"/>
        </comt:phone>
        <comt:requestStatus>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:requestStatus"/>
        </comt:requestStatus>
        <comt:technicalOrderNumber>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:technicalOrderNumber"/>
        </comt:technicalOrderNumber>
        <comt:CSOrderNumber>
          <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:CSOrderNumber"/>
        </comt:CSOrderNumber>
        <xsl:if test="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:ExpectedTechnicallyReadyToMigrateDate != &quot;&quot;">
          <comt:ExpectedTechnicallyReadyToMigrateDate>
            <xsl:value-of select="/xsdLocal:orderResponseStatus/xsdLocal:orderHeader/comt:ExpectedTechnicallyReadyToMigrateDate"/>
          </comt:ExpectedTechnicallyReadyToMigrateDate>
        </xsl:if>
      </xsdLocal:orderHeader>
      <xsl:for-each select="/xsdLocal:orderResponseStatus/xsdLocal:orderLineItem">
        <xsdLocal:orderLineItem>
          <comt:CRMOLIId>
            <xsl:value-of select="comt:CRMOLIId"/>
          </comt:CRMOLIId>
          <comt:plannedInstallationDate>
            <xsl:value-of select="comt:plannedInstallationDate"/>
          </comt:plannedInstallationDate>
          <comt:actualInstallationDate>
            <xsl:value-of select="comt:actualInstallationDate"/>
          </comt:actualInstallationDate>
          <comt:technicalFulfilmentStatus>
            <xsl:value-of select="comt:technicalFulfilmentStatus"/>
          </comt:technicalFulfilmentStatus>
        </xsdLocal:orderLineItem>
      </xsl:for-each>
    </xsdLocal:orderResponseStatus>
  </xsl:template>
</xsl:stylesheet>
