<?binding.jca INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID_db.jca?>
<wsdl:definitions name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/INTERFACEBUFFERSelectByInterfaceIDAndReferenceID">
    <plt:partnerLinkType name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID_plt">
        <plt:role name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID_role">
            <plt:portType name="tns:INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/INTERFACEBUFFERSelectByInterfaceIDAndReferenceID" schemaLocation="INTERFACEBUFFERSelectByInterfaceIDAndReferenceID_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceIDSelect_InterfaceID_ReferenceID_inparameters">
        <wsdl:part name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceIDSelect_InterfaceID_ReferenceID_inparameters" element="top:INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceIDSelect_InterfaceID_ReferenceIDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="InterfaceBufferCollection_msg">
        <wsdl:part name="InterfaceBufferCollection" element="top:InterfaceBufferCollection"/>
    </wsdl:message>
    <wsdl:portType name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceID_ptt">
        <wsdl:operation name="INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceIDSelect_InterfaceID_ReferenceID">
            <wsdl:input message="tns:INTERFACE_BUFFER_SelectByInterfaceIDAndReferenceIDSelect_InterfaceID_ReferenceID_inparameters"/>
            <wsdl:output message="tns:InterfaceBufferCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
