// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.reuters.eai.cc.uom;

public interface TransformToCSUserRequest extends java.rmi.Remote {
    public com.reuters.eai.cc.uom.CSFixedLengthUserOrderRequest transform(com.reuters.eai.cc.uom.CSUserOrderRequest parameter) throws 
         java.rmi.RemoteException;
}
