// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.3.0, build 070610.1800.23513)

package com.reuters.ns._2007._01._25.gcap.eai.cs.om.ordermanagement;


public class _CSResponseOrderHeader implements java.io.Serializable {
    protected com.reuters.ns._2007._01._25.gcap.eai.cs.om.ordermanagement.Response response;
    protected java.lang.String requestStatus;
    protected java.lang.String CRMOrderNumber;
    protected java.lang.String orderNumber;
    protected java.lang.String entrepriseCode;
    
    public _CSResponseOrderHeader() {
    }
    
    public com.reuters.ns._2007._01._25.gcap.eai.cs.om.ordermanagement.Response getResponse() {
        return response;
    }
    
    public void setResponse(com.reuters.ns._2007._01._25.gcap.eai.cs.om.ordermanagement.Response response) {
        this.response = response;
    }
    
    public java.lang.String getRequestStatus() {
        return requestStatus;
    }
    
    public void setRequestStatus(java.lang.String requestStatus) {
        this.requestStatus = requestStatus;
    }
    
    public java.lang.String getCRMOrderNumber() {
        return CRMOrderNumber;
    }
    
    public void setCRMOrderNumber(java.lang.String CRMOrderNumber) {
        this.CRMOrderNumber = CRMOrderNumber;
    }
    
    public java.lang.String getOrderNumber() {
        return orderNumber;
    }
    
    public void setOrderNumber(java.lang.String orderNumber) {
        this.orderNumber = orderNumber;
    }
    
    public java.lang.String getEntrepriseCode() {
        return entrepriseCode;
    }
    
    public void setEntrepriseCode(java.lang.String entrepriseCode) {
        this.entrepriseCode = entrepriseCode;
    }
}
