<?binding.jca SAPAM_POLLING_VIEW_db.jca?>
<definitions name="SAPAM_POLLING_VIEW" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SAPAM_POLLING_VIEW/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SAPAM_POLLING_VIEW/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SAPAMPOLLINGVIEW">
    <plt:partnerLinkType name="SAPAM_POLLING_VIEW_plt">
        <plt:role name="SAPAM_POLLING_VIEW_role">
            <plt:portType name="tns:SAPAM_POLLING_VIEW_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SAPAMPOLLINGVIEW" schemaLocation="SAPAMPOLLINGVIEW_table.xsd"/>
        </schema>
    </types>
    <message name="SapamPollingVCollection_msg">
        <part name="SapamPollingVCollection" element="top:SapamPollingVCollection"/>
    </message>
    <portType name="SAPAM_POLLING_VIEW_ptt">
        <operation name="receive">
            <input message="tns:SapamPollingVCollection_msg"/>
        </operation>
    </portType>
</definitions>
