<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CPFGPRD_FTPtoCPFG"
             targetNamespace="http://www.reuters.com/ns/2007/09/01/GCAP/CPFG/PRD/CPFGPRD_FTPtoCPFG"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://www.reuters.com/ns/2007/09/01/GCAP/CPFG/PRD/CPFGPRD_FTPtoCPFG"
             xmlns:ns1="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/ProductManagementServices"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	TYPE DEFINITION - List of services participating in this BPEL process
	The default output of the BPEL designer uses strings as input and 
	output to the BPEL Process. But you can define or import any XML 
	Schema type and use them as part of the message types.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->   
    <import namespace="http://schemas.oracle.com/bpel/extension" location="oramds:/soa/shared/bpel/RuntimeFault.wsdl"/>
	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/ProductManagementServices" schemaLocation="EAI.MSG.EXT.130_ProductReferenceDataUpdate.xsd" />
		</schema>
	</types>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	MESSAGE TYPE DEFINITION - Definition of the message types used as 
	part of the port type defintions
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->      
	<message name="CPFGPRD_FTPtoCPFGRequestMessage">
		<part name="payload" element="ns1:productReferenceDataUpdate" />
	</message>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PORT TYPE DEFINITION - A port type groups a set of operations into
	a logical service unit.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- portType implemented by the CPFGPRD_FTPtoCPFG BPEL process -->
	<portType name="CPFGPRD_FTPtoCPFG">
		<operation name="initiate">
			<input message="client:CPFGPRD_FTPtoCPFGRequestMessage"/>
		</operation>
	</portType>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PARTNER LINK TYPE DEFINITION
	the CPFGPRD_FTPtoCPFG partnerLinkType binds the provider and
	requester portType into an asynchronous conversation.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<plnk:partnerLinkType name="CPFGPRD_FTPtoCPFG">
		<plnk:role name="CPFGPRD_FTPtoCPFGProvider">
			<plnk:portType name="client:CPFGPRD_FTPtoCPFG"/>
		</plnk:role>
	</plnk:partnerLinkType>
</definitions>
