<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.SAP.OM.286_OrderRequest.xsd"/>
      <rootElement name="SAPOrderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/SAP/OrderRequest"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="SI_Create_ContractOrder_OB_Async.wsdl"/>
      <rootElement name="ZSDCONTRACT" namespace=""/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU JUL 01 10:33:38 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:p1="http://trm.com:I004:OrderProcessing:CreateContractOrder_Send" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:idoc="urn:sap-com:document:sap:idoc:messages" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:xsdLocal="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/SAP/OrderRequest" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl cmt xsd xsdLocal ns0 p1 wsdl wsu idoc wsp bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ZSDCONTRACT>
      <IDOC>
        <xsl:attribute name="BEGIN">
          <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
        </xsl:attribute>
        <EDI_DC40>
          <xsl:attribute name="SEGMENT">
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </xsl:attribute>
          <TABNAM>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </TABNAM>
          <MANDT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </MANDT>
          <DOCNUM>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </DOCNUM>
          <DOCREL>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </DOCREL>
          <STATUS>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </STATUS>
          <DIRECT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </DIRECT>
          <OUTMOD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </OUTMOD>
          <EXPRSS>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </EXPRSS>
          <TEST>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </TEST>
          <IDOCTYP>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </IDOCTYP>
          <CIMTYP>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </CIMTYP>
          <MESTYP>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </MESTYP>
          <MESCOD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </MESCOD>
          <MESFCT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </MESFCT>
          <STD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </STD>
          <STDVRS>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </STDVRS>
          <STDMES>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </STDMES>
          <SNDPOR>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDPOR>
          <SNDPRT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDPRT>
          <SNDPFC>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDPFC>
          <SNDPRN>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDPRN>
          <SNDSAD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDSAD>
          <SNDLAD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SNDLAD>
          <RCVPOR>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVPOR>
          <RCVPRT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVPRT>
          <RCVPFC>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVPFC>
          <RCVPRN>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVPRN>
          <RCVSAD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVSAD>
          <RCVLAD>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </RCVLAD>
          <CREDAT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </CREDAT>
          <CRETIM>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </CRETIM>
          <REFINT>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </REFINT>
          <REFGRP>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </REFGRP>
          <REFMES>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </REFMES>
          <ARCKEY>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </ARCKEY>
          <SERIAL>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </SERIAL>
        </EDI_DC40>
        <Z1SDCUST>
          <xsl:attribute name="SEGMENT">
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
          </xsl:attribute>
          <CUST_SOLDTO>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:SoldToAccountNumber"/>
          </CUST_SOLDTO>
          <CONTRACTING_COUNTRY>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:RCRMSAPConCountry"/>
          </CONTRACTING_COUNTRY>
          <SIEB_ORD_ID>
            <xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderHeader/xsdLocal:CRMOrderNumber"/>
          </SIEB_ORD_ID>
          <xsl:for-each select="/xsdLocal:SAPOrderRequest/xsdLocal:orderLineItem">
            <Z1SDITEM>
              <xsl:attribute name="SEGMENT">
                <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
              </xsl:attribute>
              <CUST_BILLTO>
                <xsl:value-of select="xsdLocal:BillToAccountNumber"/>
              </CUST_BILLTO>
              <CUST_SHIPTO>
                <xsl:value-of select="xsdLocal:InstallLocationAccountNumber"/>
              </CUST_SHIPTO>
              <ACTION>
                <xsl:value-of select="xsdLocal:SAPActionCode"/>
              </ACTION>
              <AKR>
                <xsl:value-of select="xsdLocal:AKR"/>
              </AKR>
              <ASSET_INT_ID>
                <xsl:value-of select="xsdLocal:assetIntegrationId"/>
              </ASSET_INT_ID>
              <xsl:choose>
                <xsl:when test="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/SAPNYSE_Subsidy.dvm&quot;,&quot;NYSEPLI&quot;,xsdLocal:PPLID,&quot;Value&quot;,&quot;N&quot;) = &quot;N&quot;">
                  <BILL_TYPE>
                    <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/BillingTypeMap.dvm&quot;,&quot;SiebelBillingType&quot;,xsdLocal:billingType,&quot;SAPBillingType&quot;,xsdLocal:billingType)"/>
                  </BILL_TYPE>
                </xsl:when>
                <xsl:otherwise>
                  <BILL_TYPE>
                    <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/BillingTypeMap.dvm&quot;,&quot;SiebelBillingType&quot;,concat(&quot;NYSE&quot;,xsdLocal:billingType),&quot;SAPBillingType&quot;,xsdLocal:billingType)"/>
                  </BILL_TYPE>
                </xsl:otherwise>
              </xsl:choose>
              <BILLING_NOTE>
                <xsl:value-of select="xsdLocal:billingNote"/>
              </BILLING_NOTE>
              <xsl:choose>
                <xsl:when test="(xsdLocal:SAPBusinessCase = &quot;New&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Start Date Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Billing Account Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Special Price Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;User Swap&quot;) or ((xsdLocal:SAPBusinessCase = &quot;AKR Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Billing Note Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;PO Number Change&quot;) or (xsdLocal:SAPBusinessCase = &quot;FT Conversion&quot;))))))))">
                  <START_DATE>
                    <xsl:value-of select="concat(substring(xsdLocal:startStopBillingDate,1.0,4.0),substring(xsdLocal:startStopBillingDate,6.0,2.0),substring(xsdLocal:startStopBillingDate,9.0,2.0))"/>
                  </START_DATE>
                </xsl:when>
                <xsl:when test="(xsdLocal:SAPBusinessCase = &quot;Stop Date Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Cancellation&quot;) or (xsdLocal:SAPBusinessCase = &quot;Cancel AddOn&quot;))">
                  <START_DATE>
                    <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
                  </START_DATE>
                </xsl:when>
                <xsl:otherwise>
                  <START_DATE>
                    <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
                  </START_DATE>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:choose>
                <xsl:when test="(xsdLocal:SAPBusinessCase = &quot;Stop Date Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Cancellation&quot;) or (xsdLocal:SAPBusinessCase = &quot;Cancel AddOn&quot;))">
                  <STOP_DATE>
                    <!--xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderLineItem/xsdLocal:startStopBillingDate"/-->
                    <xsl:value-of select="concat(substring(xsdLocal:startStopBillingDate,1.0,4.0),substring(xsdLocal:startStopBillingDate,6.0,2.0),substring(xsdLocal:startStopBillingDate,9.0,2.0))"/>
                  </STOP_DATE>
                </xsl:when>
                <xsl:when test="(xsdLocal:SAPBusinessCase = &quot;New&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Start Date Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Billing Account Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Special Price Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;User Swap&quot;) or ((xsdLocal:SAPBusinessCase = &quot;AKR Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;Billing Note Change&quot;) or ((xsdLocal:SAPBusinessCase = &quot;PO Number Change&quot;) or (xsdLocal:SAPBusinessCase = &quot;FT Conversion&quot;))))))))">
                  <STOP_DATE>
                    <!--xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderLineItem/xsdLocal:startStopBillingDate"/-->
                    <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
                  </STOP_DATE>
                </xsl:when>
                <xsl:otherwise>
                  <STOP_DATE>
                    <!--xsl:value-of select="/xsdLocal:SAPOrderRequest/xsdLocal:orderLineItem/xsdLocal:startStopBillingDate"/-->
                    <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:tempOrderVar"/>
                  </STOP_DATE>
                </xsl:otherwise>
              </xsl:choose>
              <OPERATION>
                <xsl:value-of select="xsdLocal:SAPBusinessCase"/>
              </OPERATION>
              <CR_DR>
                <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/BillingTypeMap.dvm&quot;,&quot;SiebelBillingType&quot;,xsdLocal:billingType,&quot;CR_DR&quot;,xsdLocal:billingType)"/>
              </CR_DR>
              <PO_NO>
                <xsl:value-of select="xsdLocal:PONumber"/>
              </PO_NO>
              <QTY>
                <xsl:value-of select="xsdLocal:quantity"/>
              </QTY>
              <QUOTE_NO>
                <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:quoteNumber"/>
              </QUOTE_NO>
              <SPEC_PRICE>
                <xsl:value-of select="xsdLocal:specialPrice"/>
              </SPEC_PRICE>
              <EDL_PRICE>
                <xsl:value-of select="xsdLocal:ListPrice"/>
              </EDL_PRICE>
              <SIEB_ORLIN_ID>
                <xsl:value-of select="xsdLocal:CRMOLIId"/>
              </SIEB_ORLIN_ID>
              <REC_BIL_FLG>
                <xsl:value-of select="xsdLocal:RCRMField1"/>
              </REC_BIL_FLG>
              <SPEC_PRICE_CURR>
                <xsl:value-of select="xsdLocal:specialPriceCurr"/>
              </SPEC_PRICE_CURR>
              <SPEC_PRICE_EDATE>
                <xsl:value-of select="concat(substring(xsdLocal:specialPriceRestrictionDate,1.0,4.0),substring(xsdLocal:specialPriceRestrictionDate,6.0,2.0),substring(xsdLocal:specialPriceRestrictionDate,9.0,2.0))"/>
              </SPEC_PRICE_EDATE>
              <EDL_PRICE_CURR>
                <xsl:value-of select="xsdLocal:RCRMField3"/>
              </EDL_PRICE_CURR>
              <DLYD_BIL_PERIOD>
                <xsl:value-of select="xsdLocal:BillingPeriod"/>
              </DLYD_BIL_PERIOD>
              <SIEB_USER>
                <xsl:value-of select="xsdLocal:userNumber"/>
              </SIEB_USER>
              <PRODUCT>
                <xsl:value-of select="xsdLocal:PLI"/>
              </PRODUCT>
              <PROD_DESC>
                <xsl:value-of select="xsdLocal:product"/>
              </PROD_DESC>
              <PPLID>
                <xsl:value-of select="xsdLocal:PPLID"/>
              </PPLID>
              <LOGINID>
                <xsl:value-of select="xsdLocal:userID"/>
              </LOGINID>              
            </Z1SDITEM>
          </xsl:for-each>
        </Z1SDCUST>
      </IDOC>
    </ZSDCONTRACT>
  </xsl:template>
</xsl:stylesheet>
