<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CS.OM.170_OrderStatus.xsd"/>
      <rootElement name="CSorderStatus" namespace="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/CS/OM/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="AdpOrderCacheService_table.xsd"/>
      <rootElement name="OrderCacheCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/AdpOrderCacheService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI JUN 04 00:04:39 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/AdpOrderCacheService" xmlns:xsdLocal="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/CS/OM/OrderManagement" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:gcap-sa="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl xsd xsdLocal gcap-sa ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns0:OrderCacheCollection>
      <xsl:for-each select="/xsdLocal:CSorderStatus/xsdLocal:orderLineItem">
        <ns0:OrderCache>
          <ns0:crmOliId>
            <xsl:value-of select="xsdLocal:CRMOLIId"/>
          </ns0:crmOliId>
          <xsl:choose>
            <xsl:when test="(../xsdLocal:orderHeader/xsdLocal:response = &quot;0&quot;) and ((../xsdLocal:messageHeader/xsdLocal:actionCode = &quot;OM05&quot;) or ((../xsdLocal:messageHeader/xsdLocal:actionCode = &quot;OM60&quot;) or (../xsdLocal:messageHeader/xsdLocal:actionCode = &quot;OM90&quot;)))">
              <ns0:csOrdNo>
                <xsl:value-of select="../xsdLocal:orderHeader/xsdLocal:orderNumber"/>
              </ns0:csOrdNo>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="xsdLocal:orderLinestatus = &quot;P&quot;">
              <ns0:autoPermComplete>
                <xsl:text disable-output-escaping="no">Y</xsl:text>
              </ns0:autoPermComplete>
            </xsl:when>
          </xsl:choose>
        </ns0:OrderCache>
      </xsl:for-each>
    </ns0:OrderCacheCollection>
  </xsl:template>
</xsl:stylesheet>
