<?binding.jca DequeueAccountRequest_mq.jca?>
<definitions name="DequeueAccountRequest" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/mq/headerDequeueAccountRequest/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/mq/header" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/mq/headerDequeueAccountRequest/" xmlns:imp1="http://www.siebel.com/xml/RCRM%20Account%20Publish" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="Dequeue_plt">
        <plt:role name="Dequeue_role">
            <plt:portType name="tns:Dequeue_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <import namespace="http://schemas.oracle.com/bpel/extension" location="oramds:/soa/shared/bpel/RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.siebel.com/xml/RCRM%20Account%20Publish" schemaLocation="EAI.MSG.CCRM.172_PublishAccountRequestResponse.xsd"/>
        </schema>
    </types>
    <message name="AccountContactPublish_msg">
        <part name="AccountContactPublish" element="imp1:AccountContactPublish"/>
    </message>
    <portType name="Dequeue_ptt">
        <operation name="Dequeue">
            <input message="tns:AccountContactPublish_msg"/>
        </operation>
    </portType>
</definitions>
