<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.CCRM.172_PublishAccountRequestResponse.xsd"/>
      <rootElement name="AccountContactPublish" namespace="http://www.siebel.com/xml/RCRM%20Account%20Publish"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/EAIMetaData/schemas/EAI.MSG.AM.176_AccountEvent.xsd"/>
      <rootElement name="accountEvent" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/AM/AccountPublish"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [FRI SEP 16 14:55:17 IST 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:gcap-cut="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gcap-NUT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserTypes" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:gcap-NAT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableAccountTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/AM/AccountPublish" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:gcap-cat="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" xmlns:xsdLocal="http://www.siebel.com/xml/RCRM%20Account%20Publish" exclude-result-prefixes="xsl xsd xsdLocal gcap-cmt gcap-cut gcap-NUT gcap-NAT local ns0 gcap-cat bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <local:accountEvent>
      <local:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:SourceSystem"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/@MessageId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/@MessageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="string(&quot;CRM;EAI;&quot;)"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="string(0.0)"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="number(&quot;0&quot;)"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="string(&quot;A&quot;)"/>
        </gcap-cmt:payloadVersion>
      </local:eaiHeader>
      <local:publishAccountToSAP>
        <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RCRMPublishAccountToSAP"/>
      </local:publishAccountToSAP>
      <local:Timestamp>
        <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:Timestamp"/>
      </local:Timestamp>
      <local:actionCode>
        <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:ActionCode"/>
      </local:actionCode>
      <local:country>
        <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountCountry"/>
      </local:country>
      <local:account>
        <local:EikonAccountName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:EikonAccountName"/>
        </local:EikonAccountName>
        <local:RCRMFinancialCharges>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMFinancialCharges"/>
        </local:RCRMFinancialCharges>
        <local:trscAgreementNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:TRSCAgreementNumber"/>
        </local:trscAgreementNumber>
        <local:urgentBillingFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:UrgentBillingFlag"/>
        </local:urgentBillingFlag>
        <local:softDollarCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:SoftDollarCode"/>
        </local:softDollarCode>
        <local:SAPPublishedFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:SAPPublishedFlag"/>
        </local:SAPPublishedFlag>
        <local:billingLanguage>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMBillingLanguage"/>
        </local:billingLanguage>
        <local:billingCurrency>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMBillingCurrency"/>
        </local:billingCurrency>
        <local:parentCustomerReferenceNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ParentCustomerReferenceNumber"/>
        </local:parentCustomerReferenceNumber>
        <local:KNOwned>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:KNOwned"/>
        </local:KNOwned>
        <local:invoiceDeliveryMethod>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:InvoiceDeliveryMethod"/>
        </local:invoiceDeliveryMethod>
        <local:hardcopyDispatchMethod>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:HardcopyDispatchMethod"/>
        </local:hardcopyDispatchMethod>
        <local:extBillingAccountDesc>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ExtBillingAccountDesc"/>
        </local:extBillingAccountDesc>
        <local:Dummy3>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMDummy3"/>
        </local:Dummy3>
        <local:Dummy2>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMDummy2"/>
        </local:Dummy2>
        <local:Dummy1>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMDummy1"/>
        </local:Dummy1>
        <local:tomIntegrationFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMTOMIntegrationFlag"/>
        </local:tomIntegrationFlag>
        <local:CMIntegrationFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCMIntegrationFlag"/>
        </local:CMIntegrationFlag>
        <local:subRegion>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:SubRegion"/>
        </local:subRegion>
        <local:SuspendBillingFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSuspendBillingFlag"/>
        </local:SuspendBillingFlag>
        <local:TCId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMTCId"/>
        </local:TCId>
        <local:primaryAccountFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMPrimaryAccountFlag"/>
        </local:primaryAccountFlag>
        <local:PerClientBillingFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMPerClientBillingFlag"/>
        </local:PerClientBillingFlag>
        <local:oaid>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMOAID"/>
        </local:oaid>
        <local:oaName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMOAName"/>
        </local:oaName>
        <local:multiCenterNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMMultiCenterNumber"/>
        </local:multiCenterNumber>
        <local:InvoicingCenter>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMInvoicingCenter"/>
        </local:InvoicingCenter>
        <local:invoiceDescription>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMInvoiceDescription"/>
        </local:invoiceDescription>
        <local:GeoCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMGeoCode"/>
        </local:GeoCode>
        <local:CityCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCityCode"/>
        </local:CityCode>
        <local:csIntegrationFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCSIntegrationFlag"/>
        </local:csIntegrationFlag>
        <local:alternateSubscriberNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAlternateSubscriberNumber"/>
        </local:alternateSubscriberNumber>
        <local:addressType>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAddressType"/>
        </local:addressType>
        <local:phoneNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:MainPhoneNumber"/>
        </local:phoneNumber>
        <local:faxNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:MainFaxNumber"/>
        </local:faxNumber>
        <local:id>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Id"/>
        </local:id>
        <local:irasReference>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMIRASReference"/>
        </local:irasReference>
        <local:accountStatus>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:AccountStatus"/>
        </local:accountStatus>
        <local:contactRelationshipType>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ContactRelationshipType"/>
        </local:contactRelationshipType>
        <local:globalUltimateParentType>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:GlobalUltimateParent"/>
        </local:globalUltimateParentType>
        <local:currencyCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:CurrencyCode"/>
        </local:currencyCode>
        <local:description>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Description"/>
        </local:description>
        <local:groupTypeCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:GroupTypeCode"/>
        </local:groupTypeCode>
        <local:masterAccountId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:MasterAccountId"/>
        </local:masterAccountId>
        <local:name>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Name"/>
        </local:name>
        <local:orgId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:OrgId"/>
        </local:orgId>
        <local:parentAccountId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ParentAccountId"/>
        </local:parentAccountId>
        <local:partyName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PartyName"/>
        </local:partyName>
        <local:partyTypeCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PartyTypeCode"/>
        </local:partyTypeCode>
        <local:partyUId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PartyUId"/>
        </local:partyUId>
        <local:primaryAccountCity>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountCity"/>
        </local:primaryAccountCity>
        <local:primaryAccountCountry>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountCountry"/>
        </local:primaryAccountCountry>
        <local:primaryAccountPostalCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountPostalCode"/>
        </local:primaryAccountPostalCode>
        <local:primaryAccountState>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountState"/>
        </local:primaryAccountState>
        <local:primaryAccountStreetAddress>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAccountStreetAddress"/>
        </local:primaryAccountStreetAddress>
        <local:primaryAddressId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAddressId"/>
        </local:primaryAddressId>
        <local:primaryAddressName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryAddressName"/>
        </local:primaryAddressName>
        <local:primaryContactId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryContactId"/>
        </local:primaryContactId>
        <local:primaryPositionId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:PrimaryPositionId"/>
        </local:primaryPositionId>
        <local:accountClass>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAccountClass"/>
        </local:accountClass>
        <local:accountFamily>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAccountFamily"/>
        </local:accountFamily>
        <local:billingFrequency>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMBillingFrequency"/>
        </local:billingFrequency>
        <local:businessChannel>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMBusinessChannel"/>
        </local:businessChannel>
         <local:RelationShipModel>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMRelationShipModel"/>
        </local:RelationShipModel>
        <local:coreSuiteStatus>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCoreSuiteStatus"/>
        </local:coreSuiteStatus>
        <local:errorMessage>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMErrorMessage"/>
        </local:errorMessage>
        <local:fieldServiceLocation>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMFieldServiceLocation"/>
        </local:fieldServiceLocation>
        <local:internalAccountFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMInternalAccountFlag"/>
        </local:internalAccountFlag>
        <local:organisationType>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMOrganisationType"/>
        </local:organisationType>
        <local:organisationTypeDesc>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMOrganisationTypeDesc"/>
        </local:organisationTypeDesc>
        <local:payTerms>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMPayTerms"/>
        </local:payTerms>
        <local:primaryChildId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMPrimaryChildId"/>
        </local:primaryChildId>
        <local:quotronClient>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMQuotronClient"/>
        </local:quotronClient>
        <local:region>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMRegion"/>
        </local:region>
        <local:subAccountName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubAccountName"/>
        </local:subAccountName>
        <local:subAccountNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubAccountNumber"/>
        </local:subAccountNumber>
        <local:subscriberCountry>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubscriberCountry"/>
        </local:subscriberCountry>
        <local:subscriberCountryCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubscriberCountryCode"/>
        </local:subscriberCountryCode>
        <local:subscriberNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubscriberNumber"/>
        </local:subscriberNumber>
        <local:subscriberShortName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSubscriberShortName"/>
        </local:subscriberShortName>
        <local:sysUpdatedBy>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSysUpdatedBy"/>
        </local:sysUpdatedBy>
        <local:taxCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMTaxCode"/>
        </local:taxCode>
        <local:vatCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMVATCode"/>
        </local:vatCode>
        <local:site>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Site"/>
        </local:site>
        <local:SFDCID>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMSFDCId"/>
        </local:SFDCID>
        <local:HomePage>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Homepage"/>
        </local:HomePage>
        <local:Segment>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Segment"/>
        </local:Segment>
        <local:ownerMail>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Owneremail"/>
        </local:ownerMail>
        <local:masterAccountClass>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:MasterAccountClass"/>
        </local:masterAccountClass>
        <local:taxIDNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:TaxIDNumber"/>
        </local:taxIDNumber>
        <local:customerReference>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCustomerReference"/>
        </local:customerReference>
        <local:customerJourney>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCustomerJourney"/>
        </local:customerJourney>
        <local:accountNotes>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAccountNotes"/>
        </local:accountNotes>
        <local:accountDescription>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMAccountDescription"/>
        </local:accountDescription>
        <local:parentAccountClass>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ParentAccountClass"/>
        </local:parentAccountClass>
        <local:caID>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCAID"/>
        </local:caID>
        <local:TDOStatus>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMTDOCheck"/>
        </local:TDOStatus>
        <local:TDOCheckDate>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMTDOCheckPerformed"/>
        </local:TDOCheckDate>
        <local:CreditCheckStatus>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMCreditCheck"/>
        </local:CreditCheckStatus>
        <local:CreditCheckDate>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:CreditStatusDate"/>
        </local:CreditCheckDate>
        <local:ContractType>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMContractType"/>
        </local:ContractType>
        <local:AccountTypeCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:AccountTypeCode"/>
        </local:AccountTypeCode>
        <local:siebelAccountStatus>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:AccountStatus"/>
        </local:siebelAccountStatus>
        <local:lastUpdated>
          <xsl:value-of select="xp20:upper-case(/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:LastUpdatedBy)"/>
        </local:lastUpdated>
        <local:customerReferenceNumber>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:CustomerReferenceNumber"/>
        </local:customerReferenceNumber>
        <local:localAccountName>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalAccountName"/>
        </local:localAccountName>
        <local:legalEntityFlag>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLegalEntityFlag"/>
        </local:legalEntityFlag>
        <local:localStreetAddress>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalStreetAddress"/>
        </local:localStreetAddress>
        <local:localCity>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalCity"/>
        </local:localCity>
        <local:localState>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalState"/>
        </local:localState>
        <local:localCountry>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalCountry"/>
        </local:localCountry>
        <local:localPostalCode>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMLocalPostalCode"/>
        </local:localPostalCode>
        <local:trscFields>
          <local:TRSCversion>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMTRSCVersion"/>
          </local:TRSCversion>
          <local:TRSCStartDate>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementStartDate"/>
          </local:TRSCStartDate>
          <local:TRSCEndDate>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementEndDate"/>
          </local:TRSCEndDate>
          <local:NonStdPriceAdjClause>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMNonStdPriceAdjClause"/>
          </local:NonStdPriceAdjClause>
          <local:AgreementType>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementType"/>
          </local:AgreementType>
          <local:AgreementStatus>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementStatus"/>
          </local:AgreementStatus>
          <local:AgreementNumber>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementNumber"/>
          </local:AgreementNumber>
          <local:TermStatus>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMTermStatus"/>
          </local:TermStatus>
          <local:TRBPVersion>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMTRBPVersion"/>
          </local:TRBPVersion>
          <local:Dummy3>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMDummy3"/>
          </local:Dummy3>
          <local:Dummy2>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMDummy2"/>
          </local:Dummy2>
          <local:Dummy1>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMDummy1"/>
          </local:Dummy1>
          <local:ContractDetail>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:RCRMContractDetail"/>
          </local:ContractDetail>
          <local:Name>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:Name"/>
          </local:Name>
          <local:Id>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:Id"/>
          </local:Id>
          <local:Discount>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:Discount"/>
          </local:Discount>
          <local:AgreementId>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:ServiceAgreement/xsdLocal:AgreementId"/>
          </local:AgreementId>
        </local:trscFields>
        <local:trbcFields>
          <local:industryType>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:TRBCIndustryType"/>
          </local:industryType>
          <local:industrySubType>
            <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:TRBCIndustrySubType"/>
          </local:industrySubType>
        </local:trbcFields>
        <local:customerGroup>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RCRMNOMCustGroup"/>
        </local:customerGroup>
        <local:LegacyParentId>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:LegacyParentId"/>
        </local:LegacyParentId>
        <local:localFloorAddress>
          <xsl:value-of select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:CutAddress/xsdLocal:RCRMLocalFloorAddress"/>
        </local:localFloorAddress>
       </local:account>
      <xsl:for-each select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:CutAddress">
        <local:accountAddress>
          <local:faxNumber>
            <xsl:value-of select="xsdLocal:Mainfaxnumber"/>
          </local:faxNumber>
          <local:id>
            <xsl:value-of select="xsdLocal:Id"/>
          </local:id>
          <local:accountId>
            <xsl:value-of select="xsdLocal:AccountId"/>
          </local:accountId>
          <local:accountLoc>
            <xsl:value-of select="xsdLocal:AccountLoc"/>
          </local:accountLoc>
          <local:accountName>
            <xsl:value-of select="xsdLocal:AccountName"/>
          </local:accountName>
          <local:accountPrimaryAddressId>
            <xsl:value-of select="xsdLocal:AccountPrimaryAddressId"/>
          </local:accountPrimaryAddressId>
          <local:activeStatus>
            <xsl:value-of select="xsdLocal:ActiveStatus"/>
          </local:activeStatus>
          <local:addrDescription>
            <xsl:value-of select="xsdLocal:AddrDescription"/>
          </local:addrDescription>
          <local:addressId>
            <xsl:value-of select="xsdLocal:AddressId"/>
          </local:addressId>
          <local:addressName>
            <xsl:value-of select="xsdLocal:AddressName"/>
          </local:addressName>
          <local:addressType>
            <xsl:value-of select="xsdLocal:AddressType"/>
          </local:addressType>
          <local:apartmentNumber>
            <xsl:value-of select="xsdLocal:ApartmentNumber"/>
          </local:apartmentNumber>
          <local:billAddressFlag>
            <xsl:value-of select="xsdLocal:BillAddressFlag"/>
          </local:billAddressFlag>
          <local:city>
            <xsl:value-of select="xsdLocal:City"/>
          </local:city>
          <local:contactId>
            <xsl:value-of select="xsdLocal:ContactId"/>
          </local:contactId>
          <local:country>
            <xsl:value-of select="xsdLocal:Country"/>
          </local:country>
          <local:county>
            <xsl:value-of select="xsdLocal:County"/>
          </local:county>
          <local:descriptor>
            <xsl:value-of select="xsdLocal:Descriptor"/>
          </local:descriptor>
          <local:emailAddress>
            <xsl:value-of select="xsdLocal:EmailAddress"/>
          </local:emailAddress>
          <local:integrationId>
            <xsl:value-of select="xsdLocal:IntegrationId"/>
          </local:integrationId>
          <local:landlordName>
            <xsl:value-of select="xsdLocal:LandlordName"/>
          </local:landlordName>
          <local:landlordPhoneNumber>
            <xsl:value-of select="xsdLocal:LandlordPhoneNumber"/>
          </local:landlordPhoneNumber>
          <local:lastUpdatedConAddr>
            <xsl:value-of select="xsdLocal:LastUpdatedConAddr"/>
          </local:lastUpdatedConAddr>
          <local:localOperatingCompany>
            <xsl:value-of select="xsdLocal:LocalOperatingCompany"/>
          </local:localOperatingCompany>
          <local:localOperatingCompanyId>
            <xsl:value-of select="xsdLocal:LocalOperatingCompanyId"/>
          </local:localOperatingCompanyId>
          <local:localOperatingCompanySite>
            <xsl:value-of select="xsdLocal:LocalOperatingCompanySite"/>
          </local:localOperatingCompanySite>
          <local:mainAddressFlag>
            <xsl:value-of select="xsdLocal:MainAddressFlag"/>
          </local:mainAddressFlag>
          <local:parentAddress>
            <xsl:value-of select="xsdLocal:ParentAddress"/>
          </local:parentAddress>
          <local:parentAddressId>
            <xsl:value-of select="xsdLocal:ParentAddressId"/>
          </local:parentAddressId>
          <local:phoneNumber>
            <xsl:value-of select="xsdLocal:PhoneNumber"/>
          </local:phoneNumber>
          <local:postalCode>
            <xsl:value-of select="xsdLocal:PostalCode"/>
          </local:postalCode>
          <local:province>
            <xsl:value-of select="xsdLocal:Province"/>
          </local:province>
          <local:rcrmaddressType>
            <xsl:value-of select="xsdLocal:RCRMAddressType"/>
          </local:rcrmaddressType>
          <local:csaddressType>
            <xsl:value-of select="xsdLocal:RCRMCSAddressType"/>
          </local:csaddressType>
          <local:streetAddress>
            <xsl:value-of select="xsdLocal:StreetAddress"/>
          </local:streetAddress>
          <local:streetAddress2>
            <xsl:value-of select="xsdLocal:StreetAddress2"/>
          </local:streetAddress2>
          <local:rcrmemailAddress>
            <xsl:value-of select="xsdLocal:RCRMEmailAddress"/>
          </local:rcrmemailAddress>
          <local:floorAddress>
            <xsl:value-of select="xsdLocal:RCRMFloorAddress"/>
          </local:floorAddress>
          <local:legacyAddressRef>
            <xsl:value-of select="xsdLocal:RCRMLegacyAddressRef"/>
          </local:legacyAddressRef>
          <local:legacyFlag>
            <xsl:value-of select="xsdLocal:RCRMLegacyFlag"/>
          </local:legacyFlag>
          <local:localStreet>
            <xsl:value-of select="xsdLocal:RCRMLocalStreetAddress"/>
          </local:localStreet>
          <local:localCity>
            <xsl:value-of select="xsdLocal:RCRMLocalCity"/>
          </local:localCity>
          <local:localCountry>
            <xsl:value-of select="xsdLocal:RCRMLocalCountry"/>
          </local:localCountry>
          <local:localPostalCode>
            <xsl:value-of select="xsdLocal:RCRMLocalPostalCode"/>
          </local:localPostalCode>
          <local:localState>
            <xsl:value-of select="xsdLocal:RCRMLocalState"/>
          </local:localState>
          <local:region>
            <xsl:value-of select="xsdLocal:RCRMRegion"/>
          </local:region>
          <local:rowId>
            <xsl:value-of select="xsdLocal:RowId"/>
          </local:rowId>
          <local:sInstance>
            <xsl:value-of select="xsdLocal:S-SInstance"/>
          </local:sInstance>
          <local:sInstanceId>
            <xsl:value-of select="xsdLocal:S-SInstanceId"/>
          </local:sInstanceId>
          <local:skeyId>
            <xsl:value-of select="xsdLocal:S-SKeyId"/>
          </local:skeyId>
          <local:state>
            <xsl:value-of select="xsdLocal:State"/>
          </local:state>
          <local:subRegion>
            <xsl:value-of select="xsdLocal:SubRegion"/>
          </local:subRegion>
          <local:type>
            <xsl:value-of select="xsdLocal:Type"/>
          </local:type>
          <local:verifiedFlag>
            <xsl:value-of select="xsdLocal:VerifiedFlag"/>
          </local:verifiedFlag>
        </local:accountAddress>
      </xsl:for-each>
      <xsl:for-each select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:Position">
        <local:employee>
          <local:publishContactToSAP>
            <xsl:value-of select="xsdLocal:RCRMPublishContactToSAP"/>
          </local:publishContactToSAP>
          <local:positionType>
            <xsl:value-of select="xsdLocal:PositionType"/>
          </local:positionType>
          <local:contactWorkNumber>
            <xsl:value-of select="xsdLocal:ContactWorkNumber"/>
          </local:contactWorkNumber>
          <local:contactState>
            <xsl:value-of select="xsdLocal:ContactState"/>
          </local:contactState>
          <local:contactPostalCode>
            <xsl:value-of select="xsdLocal:ContactPostalCode"/>
          </local:contactPostalCode>
          <local:contactFaxNumber>
            <xsl:value-of select="xsdLocal:ContactFaxNumber"/>
          </local:contactFaxNumber>
          <local:contactCountry>
            <xsl:value-of select="xsdLocal:ContactCountry"/>
          </local:contactCountry>
          <local:contactCity>
            <xsl:value-of select="xsdLocal:ContactCity"/>
          </local:contactCity>
          <local:contactAddress>
            <xsl:value-of select="xsdLocal:ContactAddress"/>
          </local:contactAddress>
          <local:contactAccountNumber>
            <xsl:value-of select="xsdLocal:ContactAccountNumber"/>
          </local:contactAccountNumber>
          <local:Dummy1>
            <xsl:value-of select="xsdLocal:RCRMDummy1"/>
          </local:Dummy1>
          <local:id>
            <xsl:value-of select="xsdLocal:Id"/>
          </local:id>
          <local:modId>
            <xsl:value-of select="xsdLocal:ModId"/>
          </local:modId>
          <local:accountId>
            <xsl:value-of select="xsdLocal:AccountId"/>
          </local:accountId>
          <local:accountLocation>
            <xsl:value-of select="xsdLocal:AccountLocation"/>
          </local:accountLocation>
          <local:accountName2>
            <xsl:value-of select="xsdLocal:AccountName2"/>
          </local:accountName2>
          <local:accountPositionId>
            <xsl:value-of select="xsdLocal:AccountPostionId"/>
          </local:accountPositionId>
          <local:accountRowStatus>
            <xsl:value-of select="xsdLocal:AccountRowStatus"/>
          </local:accountRowStatus>
          <local:accountTeamRole>
            <xsl:value-of select="xsdLocal:AccountTeamRole"/>
          </local:accountTeamRole>
          <local:activeEmail>
            <xsl:value-of select="xsdLocal:ActiveEmail"/>
          </local:activeEmail>
          <local:activeFax>
            <xsl:value-of select="xsdLocal:ActiveFax"/>
          </local:activeFax>
          <local:activeFirstName>
            <xsl:value-of select="xsdLocal:ActiveFirstName"/>
          </local:activeFirstName>
          <local:activeJobTitle>
            <xsl:value-of select="xsdLocal:ActiveJobTitle"/>
          </local:activeJobTitle>
          <local:activeLastName>
            <xsl:value-of select="xsdLocal:ActiveLastName"/>
          </local:activeLastName>
          <local:activeLoginId>
            <xsl:value-of select="xsdLocal:ActiveLoginId"/>
          </local:activeLoginId>
          <local:activeLoginName>
            <xsl:value-of select="xsdLocal:ActiveLoginName"/>
          </local:activeLoginName>
          <local:activeMM>
            <xsl:value-of select="xsdLocal:ActiveMM"/>
          </local:activeMM>
          <local:activePagerNumber>
            <xsl:value-of select="xsdLocal:ActivePagerNumber"/>
          </local:activePagerNumber>
          <local:activePagerPIN>
            <xsl:value-of select="xsdLocal:ActivePagerPIN"/>
          </local:activePagerPIN>
          <local:activePhone>
            <xsl:value-of select="xsdLocal:ActivePhone"/>
          </local:activePhone>
          <local:contactFirstName>
            <xsl:value-of select="xsdLocal:ContactFirstName"/>
          </local:contactFirstName>
          <local:contactLastName>
            <xsl:value-of select="xsdLocal:ContactLastName"/>
          </local:contactLastName>
          <local:contactPrimaryAddressId>
            <xsl:value-of select="xsdLocal:ContactPrimaryAddressId"/>
          </local:contactPrimaryAddressId>
          <local:contactPrimaryPositionId>
            <xsl:value-of select="xsdLocal:ContactPrimaryPositionId"/>
          </local:contactPrimaryPositionId>
          <local:contactPriorityFlag>
            <xsl:value-of select="xsdLocal:ContactPriorityFlag"/>
          </local:contactPriorityFlag>
          <local:contactRowStatus>
            <xsl:value-of select="xsdLocal:ContactRowStatus"/>
          </local:contactRowStatus>
          <local:costAllocation>
            <xsl:value-of select="xsdLocal:CostAllocation"/>
          </local:costAllocation>
          <local:coverageRole>
            <xsl:value-of select="xsdLocal:CoverageRole"/>
          </local:coverageRole>
          <local:description>
            <xsl:value-of select="xsdLocal:Description"/>
          </local:description>
          <local:division>
            <xsl:value-of select="xsdLocal:Division"/>
          </local:division>
          <local:employeeId>
            <xsl:value-of select="xsdLocal:EmployeeId"/>
          </local:employeeId>
          <local:employmentStatus>
            <xsl:value-of select="xsdLocal:EmploymentStatus"/>
          </local:employmentStatus>
          <local:groupTypeCode2>
            <xsl:value-of select="xsdLocal:GroupTypeCode2"/>
          </local:groupTypeCode2>
          <local:integrationId>
            <xsl:value-of select="xsdLocal:IntegrationId"/>
          </local:integrationId>
          <local:loginId>
            <xsl:value-of select="xsdLocal:LoginId"/>
          </local:loginId>
          <local:middleName>
            <xsl:value-of select="xsdLocal:MiddleName"/>
          </local:middleName>
          <local:name2>
            <xsl:value-of select="xsdLocal:Name2"/>
          </local:name2>
          <local:opportunitySalesTeamRole>
            <xsl:value-of select="xsdLocal:OpportunitySalesTeamRole"/>
          </local:opportunitySalesTeamRole>
          <local:parentPositionId>
            <xsl:value-of select="xsdLocal:ParentPositionId"/>
          </local:parentPositionId>
          <local:parentPositionName>
            <xsl:value-of select="xsdLocal:ParentPositionName"/>
          </local:parentPositionName>
          <local:parentPrimaryPositionId>
            <xsl:value-of select="xsdLocal:ParentPrimaryPositionId"/>
          </local:parentPrimaryPositionId>
          <local:partyTypeCode2>
            <xsl:value-of select="xsdLocal:PartyTypeCode2"/>
          </local:partyTypeCode2>
          <local:partyUId2>
            <xsl:value-of select="xsdLocal:PartyUId2"/>
          </local:partyUId2>
          <local:onceOffRevenue>
            <xsl:value-of select="xsdLocal:RCRMOnceOffRevenue"/>
          </local:onceOffRevenue>
          <local:responsiblity>
            <xsl:value-of select="xsdLocal:RCRMResponsiblity"/>
          </local:responsiblity>
          <local:relationship>
            <xsl:value-of select="xsdLocal:Relationship"/>
          </local:relationship>
          <local:role>
            <xsl:value-of select="xsdLocal:Role"/>
          </local:role>
          <local:rowId>
            <xsl:value-of select="xsdLocal:RowId"/>
          </local:rowId>
        </local:employee>
      </xsl:for-each>
      <xsl:for-each select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RcrmContact-Thin">
        <local:contact>
          <local:Title>
            <xsl:value-of select="xsdLocal:Title"/>
          </local:Title>
          <local:SFDCId>
            <xsl:value-of select="xsdLocal:SFDCId"/>
          </local:SFDCId>
          <local:PrimaryFunction>
            <xsl:value-of select="xsdLocal:PrimaryFunction"/>
          </local:PrimaryFunction>
          <local:LocalTitle>
            <xsl:value-of select="xsdLocal:LocalTitle"/>
          </local:LocalTitle>
          <local:LocalStreet>
            <xsl:value-of select="xsdLocal:LocalStreet"/>
          </local:LocalStreet>
          <local:LocalState>
            <xsl:value-of select="xsdLocal:LocalState"/>
          </local:LocalState>
          <local:LocalPostcode>
            <xsl:value-of select="xsdLocal:LocalPostcode"/>
          </local:LocalPostcode>
          <local:LocalLastName>
            <xsl:value-of select="xsdLocal:LocalLastName"/>
          </local:LocalLastName>
          <local:LocalFirstName>
            <xsl:value-of select="xsdLocal:LocalFirstName"/>
          </local:LocalFirstName>
          <local:LocalCountry>
            <xsl:value-of select="xsdLocal:LocalCountry"/>
          </local:LocalCountry>
          <local:LocalCity>
            <xsl:value-of select="xsdLocal:LocalCity"/>
          </local:LocalCity>
          <local:EndUserActivity>
            <xsl:value-of select="xsdLocal:EndUserActivity"/>
          </local:EndUserActivity>
          <local:ContactCategory>
            <xsl:value-of select="xsdLocal:ContactCategory"/>
          </local:ContactCategory>
          <local:AssetFocus1>
            <xsl:value-of select="xsdLocal:AssetFocus1"/>
          </local:AssetFocus1>
          <local:AccountSFDCId>
            <xsl:value-of select="xsdLocal:AccountSFDCId"/>
          </local:AccountSFDCId>
          <local:id>
            <xsl:value-of select="xsdLocal:Id"/>
          </local:id>
          <local:accountId>
            <xsl:value-of select="xsdLocal:AccountId"/>
          </local:accountId>
          <local:cellularPhone>
            <xsl:value-of select="xsdLocal:CellularPhone"/>
          </local:cellularPhone>
          <local:emailAddress2>
            <xsl:value-of select="xsdLocal:EmailAddress2"/>
          </local:emailAddress2>
          <local:employeeFlag>
            <xsl:value-of select="xsdLocal:EmployeeFlag"/>
          </local:employeeFlag>
          <local:firstName>
            <xsl:value-of select="xsdLocal:FirstName"/>
          </local:firstName>
          <local:jobTitle>
            <xsl:value-of select="xsdLocal:JobTitle"/>
          </local:jobTitle>
          <local:lastName>
            <xsl:value-of select="xsdLocal:LastName"/>
          </local:lastName>
          <local:mm>
            <xsl:value-of select="xsdLocal:MM"/>
          </local:mm>
          <local:masterAccountId>
            <xsl:value-of select="xsdLocal:MasterAccountId"/>
          </local:masterAccountId>
          <local:partyTypeCD>
            <xsl:value-of select="xsdLocal:PartyTypeCD"/>
          </local:partyTypeCD>
          <local:partyUID3>
            <xsl:value-of select="xsdLocal:PartyUID3"/>
          </local:partyUID3>
          <local:personUId>
            <xsl:value-of select="xsdLocal:PersonUId"/>
          </local:personUId>
          <local:primaryPositionId>
            <xsl:value-of select="xsdLocal:PrimaryPositionId"/>
          </local:primaryPositionId>
          <local:contactSubType>
            <xsl:value-of select="xsdLocal:RCRMContactSubType"/>
          </local:contactSubType>
          <local:coreSuiteStatus>
            <xsl:value-of select="xsdLocal:RCRMCoreSuiteStatus"/>
          </local:coreSuiteStatus>
          <local:directMarketing>
            <xsl:value-of select="xsdLocal:RCRMDirectMarketing"/>
          </local:directMarketing>
          <local:errorMessage>
            <xsl:value-of select="xsdLocal:RCRMErrorMessage"/>
          </local:errorMessage>
          <local:functionId>
            <xsl:value-of select="xsdLocal:RCRMFunctionId"/>
          </local:functionId>
          <local:PreferredLanguage>
            <xsl:value-of select="xsdLocal:RCRMPreferredLanguage"/>
          </local:PreferredLanguage>
          <local:status>
            <xsl:value-of select="xsdLocal:Status"/>
          </local:status>
          <local:relationshipType>
            <xsl:value-of select="xsdLocal:RelationshipType"/>
          </local:relationshipType>
          <local:workPhone>
            <xsl:value-of select="xsdLocal:WorkPhone"/>
          </local:workPhone>
        </local:contact>
      </xsl:for-each>
      <xsl:for-each select="/xsdLocal:AccountContactPublish/xsdLocal:RcrmAccount-Thin/xsdLocal:RcrmAccountAttributes">
        <local:attributeValuePair>
          <local:AccountId>
            <xsl:value-of select="xsdLocal:RCRMAccountId"/>
          </local:AccountId>
          <local:AttributeName>
            <xsl:value-of select="xsdLocal:AccountAttribute"/>
          </local:AttributeName>
          <local:AttributeValue>
            <xsl:value-of select="xsdLocal:AttributeValue"/>
          </local:AttributeValue>
        </local:attributeValuePair>
      </xsl:for-each>
    </local:accountEvent>
  </xsl:template>
</xsl:stylesheet>
