<definitions
    
     targetNamespace="http://soap.sforce.com/schemas/class/EAItoESO"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://soap.sforce.com/schemas/class/EAItoESO"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <import namespace="http://soap.sforce.com/schemas/class/EAItoESO" location="EAI.SRV.EXT.ESO.314_PropagateESOQuoteStatus.wsdl"/>
    <plnk:partnerLinkType name="EAItoESOPortType_PL">
        <plnk:role name="EAItoESOPortType_Role">
            <plnk:portType name="tns:EAItoESOPortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
