<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.ELM.AM.301_PublishAccount.xsd"/>
      <rootElement name="AccountPublish" namespace="http://www.reuters.com/ns/2010/07/07/SAMI/ELM/AM/AccountPublish"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="AccountService.wsdl"/>
      <rootElement name="onData" namespace="http://account.service.eai.trls.thomsonreuters.com/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU DEC 01 15:49:52 IST 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:elmam="http://www.reuters.com/ns/2010/07/07/SAMI/ELM/AM/AccountPublish" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:tns="http://account.service.eai.trls.thomsonreuters.com/" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" exclude-result-prefixes="xsl xsd elmam soap tns bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <tns:onData>
      <arg0>
        <sourcesystem>
          <xsl:text disable-output-escaping="no">SIEBEL</xsl:text>
        </sourcesystem>
        <targetsystem>
          <xsl:text disable-output-escaping="no">ELM</xsl:text>
        </targetsystem>
        <messageid>
          <xsl:text disable-output-escaping="no">''</xsl:text>
        </messageid>
        <timestamp>
          <xsl:value-of select="/elmam:AccountPublish/elmam:timeStamp"/>
        </timestamp>
        <account>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:Name"/>
        </account>
        <site>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:site"/>
        </site>
        <siebelAccountRowId>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Id"/>
        </siebelAccountRowId>
        <address>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Address/elmam:AddressName_Street"/>
        </address>
        <city>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Address/elmam:City"/>
        </city>
        <subscriberNo>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:subscribernumber"/>
        </subscriberNo>
        <state>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Address/elmam:State"/>
        </state>
        <country>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Address/elmam:Country"/>
        </country>
        <accountNumber>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:CustomerRefereceNumber"/>
        </accountNumber>
        <accountHeirachyType>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:AccountClass"/>
        </accountHeirachyType>
        <accountFamily>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:AccountFamily"/>
        </accountFamily>
        <status>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:AccountStatus"/>
        </status>
        <region>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Address/elmam:Region"/>
        </region>
        <internalAccountFlag>
          <xsl:value-of select="/elmam:AccountPublish/elmam:Accounts/elmam:internalaccountflag"/>
        </internalAccountFlag>
      </arg0>
    </tns:onData>
  </xsl:template>
</xsl:stylesheet>
