<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="EAI.SRV.EXT.SFDC.049_SendAccountToSFDCService.wsdl"/>
      <rootElement name="publishAccountResponse" namespace="http://soap.sforce.com/schemas/class/AccountManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="EAI.SRV.EXT.SFDC.049_SendAccountToSFDCService.wsdl"/>
      <rootElement name="publishAccountResponse" namespace="http://soap.sforce.com/schemas/class/AccountManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [THU DEC 29 16:41:40 GMT+05:30 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns="http://soap.sforce.com/schemas/class/AccountManagement"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsd soap tns bpws xp20 mhdr bpel orcl dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <tns:publishAccountResponse>
      <tns:result>
        <tns:BusinessChannel>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:BusinessChannel"/>
        </tns:BusinessChannel>
        <tns:Comments>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:Comments"/>
        </tns:Comments>
        <tns:RelationshipModel>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:RelationshipModel"/>
        </tns:RelationshipModel>
        <tns:SFDCId>
          <xsl:value-of select='xref:populateXRefRow("oramds:/apps/EAIMetaData/Xref/CRM_SFDC_ACCTXREF.xref","SIEBELID",/tns:publishAccountResponse/tns:result/tns:SiebelId,"SFDCID",/tns:publishAccountResponse/tns:result/tns:SFDCId,"ADD")'/>
        </tns:SFDCId>
        <tns:SiebelId>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:SiebelId"/>
        </tns:SiebelId>
        <tns:StatusCode>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:StatusCode"/>
        </tns:StatusCode>
        <tns:StatusDescription>
          <xsl:value-of select="/tns:publishAccountResponse/tns:result/tns:StatusDescription"/>
        </tns:StatusDescription>
      </tns:result>
    </tns:publishAccountResponse>
  </xsl:template>
</xsl:stylesheet>
