<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="EAI.MSG.ATH.UOM.304_UserOrderResponse.xsd"/>
      <rootElement name="userProvisionResponse" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/ATH/UOM/UserOrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://inkaban3ua-eai01:7777/orabpel/ccrmasync/OM_ManageOrderLineStatus/EAI.MSG.OM.141_OrderStatus.xsd"/>
      <rootElement name="orderStatus" namespace="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [SUN NOV 07 18:42:49 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/ATH/UOM/UserOrderManagement" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsdLocal="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:gcap-cuot="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserOrderTypes" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gcap-nuot="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserOrderTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl gcap-cmt xsd local gcap-cuot gcap-nuot ns0 xsdLocal bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <xsdLocal:orderStatus>
      <xsdLocal:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/local:userProvisionResponse/local:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </xsdLocal:eaiHeader>
      <xsdLocal:messageHeader>
        <xsdLocal:actionCode>
          <xsl:value-of select="/local:userProvisionResponse/local:userMessageHeader/local:ActionCode"/>
        </xsdLocal:actionCode>
        <xsdLocal:version>
          <xsl:value-of select="string(&quot;A&quot;)"/>
        </xsdLocal:version>
        <xsdLocal:userId>
          <xsl:value-of select="string(&quot;&quot;)"/>
        </xsdLocal:userId>
      </xsdLocal:messageHeader>
      <xsdLocal:orderHeader>
        <xsdLocal:response>
          <xsl:value-of select="string(&quot;&quot;)"/>
        </xsdLocal:response>
        <xsdLocal:requestStatus>
          <xsl:value-of select="/local:userProvisionResponse/local:userMessageHeader/local:RequestStage"/>
        </xsdLocal:requestStatus>
        <xsdLocal:CRMOrderNumber>
          <xsl:value-of select="/local:userProvisionResponse/local:userMessageHeader/local:orderNumber"/>
        </xsdLocal:CRMOrderNumber>
        <xsdLocal:orderNumber>
          <xsl:value-of select="string(&quot;&quot;)"/>
        </xsdLocal:orderNumber>
        <xsdLocal:entrepriseCode>
          <xsl:value-of select="string(&quot;&quot;)"/>
        </xsdLocal:entrepriseCode>
      </xsdLocal:orderHeader>
      <xsl:for-each select="/local:userProvisionResponse/local:userMessageBody/local:portfolioList/local:productLineReferenceNumber">
        <xsl:choose>
          <xsl:when test="../../../local:userMessageHeader/local:RequestStage = &quot;COMPLETION&quot;">
            <xsdLocal:orderLineItem>
              <xsdLocal:CRMOLIId>
                <xsl:value-of select="."/>
              </xsdLocal:CRMOLIId>
              <xsdLocal:rootItemId>
                <xsl:value-of select="../local:productCode"/>
              </xsdLocal:rootItemId>
              <xsdLocal:actionCode>
                <xsl:value-of select="../../local:ActionCode"/>
              </xsdLocal:actionCode>
              <xsdLocal:ILA>
                <xsl:value-of select="string(&quot;&quot;)"/>
              </xsdLocal:ILA>
              <xsdLocal:userId>
                <xsl:value-of select="../../local:UserId"/>
              </xsdLocal:userId>
              <xsdLocal:orderLinestatus>
                <xsl:text disable-output-escaping="no">Permissioned</xsl:text>
              </xsdLocal:orderLinestatus>
              <xsl:choose>
                <xsl:when test="../local:ErrorCode != &quot;&quot;">
                  <xsdLocal:requestStatus>
                    <xsl:value-of select="../local:ErrorCode"/>
                  </xsdLocal:requestStatus>
                </xsl:when>
                <xsl:otherwise>
                  <xsdLocal:requestStatus>
                    <xsl:value-of select="../../local:ErrorCode"/>
                  </xsdLocal:requestStatus>
                </xsl:otherwise>
              </xsl:choose>
              <xsdLocal:assetIntegrationId>
                <xsl:value-of select="orcl:lookup-table(&quot;ORDER_CACHE&quot;,&quot;CRM_OLI_ID&quot;,.,&quot;ASSET_INTEGRATION_ID&quot;,&quot;eai/ds/EAIReference&quot;)"/>
              </xsdLocal:assetIntegrationId>
              <xsdLocal:PermBillFlag>
                <xsl:text disable-output-escaping="no">P</xsl:text>
              </xsdLocal:PermBillFlag>
              <xsdLocal:SAPOrderNumber>
                <xsl:value-of select="../../local:subscriberNumber"/>
              </xsdLocal:SAPOrderNumber>
              <xsdLocal:SAPItemNumber>
                <xsl:value-of select="../../local:subAccount"/>
              </xsdLocal:SAPItemNumber>
              <xsdLocal:serverId>
                <xsl:value-of select="../../local:UserSettingStructure/local:Server/local:ServerName"/>
              </xsdLocal:serverId>
            </xsdLocal:orderLineItem>
          </xsl:when>
          <xsl:when test="../../local:TransactionStatus = &quot;FAILED&quot;">
            <xsdLocal:orderLineItem>
              <xsdLocal:CRMOLIId>
                <xsl:value-of select="."/>
              </xsdLocal:CRMOLIId>
              <xsdLocal:rootItemId>
                <xsl:value-of select="../local:productCode"/>
              </xsdLocal:rootItemId>
              <xsdLocal:actionCode>
                <xsl:value-of select="../../local:ActionCode"/>
              </xsdLocal:actionCode>
              <xsdLocal:ILA>
                <xsl:value-of select="string(&quot;&quot;)"/>
              </xsdLocal:ILA>
              <xsdLocal:userId>
                <xsl:value-of select="../../local:UserId"/>
              </xsdLocal:userId>
              <xsdLocal:orderLinestatus>
                <xsl:text disable-output-escaping="no">Error</xsl:text>
              </xsdLocal:orderLinestatus>
              <xsl:choose>
                <xsl:when test="../local:ErrorCode != &quot;&quot;">
                  <xsdLocal:requestStatus>
                    <xsl:value-of select="../local:ErrorCode"/>
                  </xsdLocal:requestStatus>
                </xsl:when>
                <xsl:otherwise>
                  <xsdLocal:requestStatus>
                    <xsl:value-of select="../../local:ErrorCode"/>
                  </xsdLocal:requestStatus>
                </xsl:otherwise>
              </xsl:choose>
              <xsdLocal:assetIntegrationId>
                <xsl:value-of select="orcl:lookup-table(&quot;ORDER_CACHE&quot;,&quot;CRM_OLI_ID&quot;,.,&quot;ASSET_INTEGRATION_ID&quot;,&quot;eai/ds/EAIReference&quot;)"/>
              </xsdLocal:assetIntegrationId>
              <xsdLocal:PermBillFlag>
                <xsl:text disable-output-escaping="no">P</xsl:text>
              </xsdLocal:PermBillFlag>
              <xsdLocal:serverId>
                <xsl:value-of select="../../local:UserSettingStructure/local:Server/local:ServerName"/>
              </xsdLocal:serverId>
            </xsdLocal:orderLineItem>
          </xsl:when>
        </xsl:choose>
      </xsl:for-each>
    </xsdLocal:orderStatus>
  </xsl:template>
</xsl:stylesheet>
