<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://inkaban3ua-eai01:7777/orabpel/ccrmasync/OM_ManageOrderLineStatus/EAI.MSG.OM.141_OrderStatus.xsd"/>
      <rootElement name="orderStatus" namespace="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://inkaban3ua-eai01:7777/orabpel/ccrmasync/OM_ManageOrderLineStatus/EAI.MSG.OM.180_ExtendedOrderStatus.xsd"/>
      <rootElement name="orderStatus" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/OrderManagement"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU NOV 04 18:15:06 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/ATH/UOM/UserOrderManagement" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsdLocal="http://www.reuters.com/NS/2007/01/25/GCAP/EAI/OrderManagement" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/OrderManagement" xmlns:gcap-cuot="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserOrderTypes" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:gcap-nuot="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserOrderTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" exclude-result-prefixes="xsl gcap-cmt xsd xsdLocal ns0 ns1 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns1:orderStatus>
      <ns1:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </ns1:eaiHeader>
      <ns1:messageHeader>
        <ns1:actionCode>
          <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,/xsdLocal:orderStatus/xsdLocal:orderLineItem/xsdLocal:CRMOLIId,&quot;ACTION_CODE&quot;,&quot;eai/ds/EAIReference&quot;)"/>
        </ns1:actionCode>
        <ns1:version>
          <xsl:value-of select="string(&quot;A&quot;)"/>
        </ns1:version>
        <ns1:userId>
          <xsl:value-of select="string(&quot;&quot;)"/>
        </ns1:userId>
      </ns1:messageHeader>
      <ns1:logicalCountry>
        <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,/xsdLocal:orderStatus/xsdLocal:orderLineItem/xsdLocal:CRMOLIId,&quot;COUNTRY&quot;,&quot;eai/ds/EAIReference&quot;)"/>
      </ns1:logicalCountry>
      <ns1:orderHeader>
        <ns1:response>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:orderHeader/xsdLocal:response"/>
        </ns1:response>
        <ns1:requestStatus>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:orderHeader/xsdLocal:requestStatus"/>
        </ns1:requestStatus>
        <ns1:CRMOrderNumber>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:orderHeader/xsdLocal:CRMOrderNumber"/>
        </ns1:CRMOrderNumber>
        <ns1:orderNumber>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:orderHeader/xsdLocal:orderNumber"/>
        </ns1:orderNumber>
        <ns1:entrepriseCode>
          <xsl:value-of select="/xsdLocal:orderStatus/xsdLocal:orderHeader/xsdLocal:entrepriseCode"/>
        </ns1:entrepriseCode>
      </ns1:orderHeader>
      <xsl:for-each select="/xsdLocal:orderStatus/xsdLocal:orderLineItem">
        <ns1:orderLineItem>
          <ns1:CRMOLIId>
            <xsl:value-of select="xsdLocal:CRMOLIId"/>
          </ns1:CRMOLIId>
          <ns1:actionCode>
            <xsl:value-of select="xsdLocal:actionCode"/>
          </ns1:actionCode>
          <ns1:rootItemId>
            <xsl:value-of select="xsdLocal:rootItemId"/>
          </ns1:rootItemId>
          <ns1:itemNumber>
            <xsl:value-of select="xsdLocal:itemNumber"/>
          </ns1:itemNumber>
          <ns1:SAPItemNumber>
            <xsl:value-of select="xsdLocal:SAPItemNumber"/>
          </ns1:SAPItemNumber>
          <ns1:SAPOrderNumber>
            <xsl:value-of select="xsdLocal:SAPOrderNumber"/>
          </ns1:SAPOrderNumber>
          <ns1:ILA>
            <xsl:value-of select="xsdLocal:ILA"/>
          </ns1:ILA>
          <ns1:userNumber>
            <xsl:value-of select="xsdLocal:userNumber"/>
          </ns1:userNumber>
          <ns1:userId>
            <xsl:value-of select="substring(xsdLocal:userId,1.0,6.0)"/>
          </ns1:userId>
          <ns1:QUID>
            <xsl:value-of select="substring(concat(substring(xsdLocal:userId,7.0,4.0),&quot;     &quot;),1.0,5.0)"/>
          </ns1:QUID>
          <ns1:orderLinestatus>
            <xsl:value-of select="xsdLocal:orderLinestatus"/>
          </ns1:orderLinestatus>
          <ns1:orderPermissionStatus>
            <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,xsdLocal:CRMOLIId,&quot;FULFILMENT_STATUS&quot;,&quot;eai/ds/EAIReference&quot;)"/>
          </ns1:orderPermissionStatus>
          <ns1:requestStatus>
            <xsl:value-of select="xsdLocal:requestStatus"/>
          </ns1:requestStatus>
          <ns1:assetIntegrationId>
            <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,xsdLocal:CRMOLIId,&quot;ASSET_INTEGRATION_ID&quot;,&quot;eai/ds/EAIReference&quot;)"/>
          </ns1:assetIntegrationId>
          <ns1:permissioningSystem>
            <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,xsdLocal:CRMOLIId,&quot;PERMISSIONING_SYSTEM&quot;,&quot;eai/ds/EAIReference&quot;)"/>
          </ns1:permissioningSystem>
          <ns1:SID>
            <xsl:value-of select="xsdLocal:SID"/>
          </ns1:SID>
          <ns1:billingPlatform>
            <xsl:value-of select="orcl:lookup-table(&quot;Order_Cache&quot;,&quot;CRM_OLI_ID&quot;,xsdLocal:CRMOLIId,&quot;BILLINGPLATFORM&quot;,&quot;eai/ds/EAIReference&quot;)"/>
          </ns1:billingPlatform>
          <ns1:permBillFlag>
            <xsl:value-of select="xsdLocal:PermBillFlag"/>
          </ns1:permBillFlag>
          <ns1:serverId>
            <xsl:value-of select="xsdLocal:serverId"/>
          </ns1:serverId>
        </ns1:orderLineItem>
      </xsl:for-each>
    </ns1:orderStatus>
  </xsl:template>
</xsl:stylesheet>
