<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/EAIMetaData/schemas/EAI.MSG.CM.197_ContactEvent.xsd"/>
      <rootElement name="contactEvent" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CM/ContactPublish"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.TOM.CM.198_PublishContactEventRequest.xsd"/>
      <rootElement name="pubContactRequest" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/TOM/ContactPublish"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU JUL 15 16:12:27 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CM/ContactPublish" xmlns:gcap-cut="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:gcap-NAT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableAccountTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/TOM/ContactPublish" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:gcap-cat="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" exclude-result-prefixes="xsl gcap-cmt local gcap-cut xsd gcap-NAT ns0 gcap-cat ns1 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns1:pubContactRequest>
      <ns1:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/local:contactEvent/local:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </ns1:eaiHeader>
      <ns1:actionCode>
        <xsl:value-of select="/local:contactEvent/local:actionCode"/>
      </ns1:actionCode>
      <ns1:contact>
        <ns1:UUID>
          <xsl:value-of select="/local:contactEvent/local:contact/local:UUID"/>
        </ns1:UUID>
        <ns1:parentAccountID>
          <xsl:value-of select="/local:contactEvent/local:contact/local:parentAccountID"/>
        </ns1:parentAccountID>
        <ns1:masterAccountID>
          <xsl:value-of select="/local:contactEvent/local:contact/local:masterAccountID"/>
        </ns1:masterAccountID>
        <ns1:firstName>
          <xsl:value-of select="/local:contactEvent/local:contact/local:firstName"/>
        </ns1:firstName>
        <ns1:lastName>
          <xsl:value-of select="/local:contactEvent/local:contact/local:lastName"/>
        </ns1:lastName>
        <ns1:telNumber>
          <xsl:value-of select="/local:contactEvent/local:contact/local:telNumber"/>
        </ns1:telNumber>
        <ns1:emailAddress>
          <xsl:value-of select="/local:contactEvent/local:contact/local:emailAddress"/>
        </ns1:emailAddress>
        <ns1:contactSubType>
          <xsl:value-of select="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/TOMCM_ContactEventConsumerContactTypeMap.dvm&quot;,&quot;EAI_CONTACT_TYPE&quot;,/local:contactEvent/local:contact/local:contactSubType,&quot;TOM_CONTACT_TYPE&quot;,&quot;UNKNOWN&quot;)"/>
        </ns1:contactSubType>
        <xsl:for-each select="/local:contactEvent/local:contact/local:clientContactJobFunctionList">
          <xsl:if test="dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/TOMCM_InvokerJobFunctionsMap.dvm&quot;,&quot;jobFunction&quot;,local:clientContactJobFunction,&quot;isValid&quot;,&quot;false&quot;) = &quot;true&quot;">
            <ns1:clientContactJobFunctionList>
              <ns1:clientContactJobFunction>
                <xsl:value-of select="local:clientContactJobFunction"/>
              </ns1:clientContactJobFunction>
              <ns1:id>
                <xsl:value-of select="local:AccountId"/>
              </ns1:id>
            </ns1:clientContactJobFunctionList>
          </xsl:if>
        </xsl:for-each>
        <!--<ns1:clientContactAccountList>
          <xsl:for-each select="/local:contactEvent/local:contact/local:clientContactAccountList/local:account">
            <ns1:account>
              <ns1:id>
                <xsl:value-of select="local:id"/>
              </ns1:id>
            </ns1:account>
          </xsl:for-each>
        </ns1:clientContactAccountList>-->
        <ns1:employeePositionList>
          <xsl:for-each select="/local:contactEvent/local:contact/local:employeePositionList/local:employeePosition">
            <ns1:employeePosition>
              <ns1:name>
                <xsl:value-of select="local:name"/>
              </ns1:name>
              <ns1:isPrimaryPosition>
                <xsl:value-of select="local:isPrimaryPosition"/>
              </ns1:isPrimaryPosition>
              <ns1:accountList>
                <xsl:for-each select="local:accountList/local:account">
                  <ns1:account>
                    <ns1:id>
                      <xsl:value-of select="local:id"/>
                    </ns1:id>
                    <ns1:isPrimaryPosition>
                      <xsl:value-of select="local:isPrimaryPosition"/>
                    </ns1:isPrimaryPosition>
                  </ns1:account>
                </xsl:for-each>
              </ns1:accountList>
            </ns1:employeePosition>
          </xsl:for-each>
        </ns1:employeePositionList>
      </ns1:contact>
    </ns1:pubContactRequest>
  </xsl:template>
</xsl:stylesheet>
