<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../EAI.SRV.EXT.RCRM.330_QueryAssetRequest.wsdl"/>
      <rootElement name="RCRMAssetData_Output" namespace="http://www.reuters.com/ns/2011/06/29/GCAP/RCRM"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../EAI.MSG.ESO.ASSET.331_AssetDataService.wsdl"/>
      <rootElement name="assetDataResponseElement" namespace="http://www.reuters.com/ns/2012/01/07/ESO/MTR/AssetDataRequest"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [WED JAN 18 16:52:02 GMT+05:30 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsdLocal="http://www.reuters.com/ns/2012/01/07/ESO/MTR/AssetDataRequest"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:tns="http://www.reuters.com/ns/2011/06/29/GCAP/RCRM"
                xmlns:xsdLocal1="http://www.siebel.com/xml/RCRMGenericAssetDetails"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soapenc tns xsdLocal1 soap xsd xsdLocal mime wsdl http xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xsdLocal:assetDataResponseElement>
      <xsdLocal:Error_spcCode>
        <xsl:value-of select="/tns:RCRMAssetData_Output/tns:Error_spcCode"/>
      </xsdLocal:Error_spcCode>
      <xsdLocal:Error_spcMessage>
        <xsl:value-of select="/tns:RCRMAssetData_Output/tns:Error_spcMessage"/>
      </xsdLocal:Error_spcMessage>
      <xsdLocal:Object_spcId>
        <xsl:value-of select="/tns:RCRMAssetData_Output/tns:Object_spcId"/>
      </xsdLocal:Object_spcId>
      <xsdLocal:Process_spcInstance_spcId>
        <xsl:value-of select="/tns:RCRMAssetData_Output/tns:Process_spcInstance_spcId"/>
      </xsdLocal:Process_spcInstance_spcId>
      <xsdLocal:Siebel_spcOperation_spcObject_spcId>
        <xsl:value-of select="/tns:RCRMAssetData_Output/tns:Siebel_spcOperation_spcObject_spcId"/>
      </xsdLocal:Siebel_spcOperation_spcObject_spcId>
      <xsdLocal:ListOfAssetDetails>
        <xsl:for-each select="/tns:RCRMAssetData_Output/xsdLocal1:ListOfRcrmGenericAssetDetails/xsdLocal1:Assets">
          <xsdLocal:Assets>
            <xsdLocal:UnInstallDate>
              <xsl:value-of select="xsdLocal1:UnInstallDate"/>
            </xsdLocal:UnInstallDate>
            <xsdLocal:Status>
              <xsl:value-of select="xsdLocal1:Status"/>
            </xsdLocal:Status>
            <xsdLocal:StartDate>
              <xsl:value-of select="xsdLocal1:StartDate"/>
            </xsdLocal:StartDate>
            <xsdLocal:SearchSpec>
              <xsl:value-of select="xsdLocal1:SearchSpec"/>
            </xsdLocal:SearchSpec>
            <xsdLocal:RootIntegrationId>
              <xsl:value-of select="xsdLocal1:RootIntegrationId"/>
            </xsdLocal:RootIntegrationId>
            <xsdLocal:SpecialPriceDate>
              <xsl:value-of select="xsdLocal1:RCRMSpecialPriceDate"/>
            </xsdLocal:SpecialPriceDate>
            <xsdLocal:SpecialPriceCurrency>
              <xsl:value-of select="xsdLocal1:RCRMSpecialPriceCurrency"/>
            </xsdLocal:SpecialPriceCurrency>
            <xsdLocal:SpecialPrice>
              <xsl:value-of select="xsdLocal1:RCRMSpecialPrice"/>
            </xsdLocal:SpecialPrice>
            <xsdLocal:ServiceAccount>
              <xsl:value-of select="xsdLocal1:RCRMServiceAccount"/>
            </xsdLocal:ServiceAccount>
            <xsdLocal:SAPPPLId>
              <xsl:value-of select="xsdLocal1:RCRMSAPPPLId"/>
            </xsdLocal:SAPPPLId>
            <xsdLocal:RevenueType>
              <xsl:value-of select="xsdLocal1:RCRMRevenueType"/>
            </xsdLocal:RevenueType>
            <xsdLocal:RenewalTerm>
              <xsl:value-of select="xsdLocal1:RCRMRenewalTerm"/>
            </xsdLocal:RenewalTerm>
            <xsdLocal:RenewalNotificationTerm>
              <xsl:value-of select="xsdLocal1:RCRMRenewalNotificationTerm"/>
            </xsdLocal:RenewalNotificationTerm>
            <xsdLocal:RenewalDate>
              <xsl:value-of select="xsdLocal1:RCRMRenewalDate"/>
            </xsdLocal:RenewalDate>
            <xsdLocal:RenewalCancellationTerm>
              <xsl:value-of select="xsdLocal1:RCRMRenewalCancellationTerm"/>
            </xsdLocal:RenewalCancellationTerm>
            <xsdLocal:PermissioningSystem>
              <xsl:value-of select="xsdLocal1:RCRMPermissioningSystem"/>
            </xsdLocal:PermissioningSystem>
            <xsdLocal:NetPriceCurrencyCode>
              <xsl:value-of select="xsdLocal1:RCRMNetPriceCurrencyCode"/>
            </xsdLocal:NetPriceCurrencyCode>
            <xsdLocal:LatestContractNumber>
              <xsl:value-of select="xsdLocal1:RCRMLatestContractNumber"/>
            </xsdLocal:LatestContractNumber>
            <xsdLocal:LatestAgreementType>
              <xsl:value-of select="xsdLocal1:RCRMLatestAgreementType"/>
            </xsdLocal:LatestAgreementType>
            <xsdLocal:LatestAgreementTermStatus>
              <xsl:value-of select="xsdLocal1:RCRMLatestAgreementTermStatus"/>
            </xsdLocal:LatestAgreementTermStatus>
            <xsdLocal:LastBillPriceCurrencyCode>
              <xsl:value-of select="xsdLocal1:RCRMLastBillPriceCurrencyCode"/>
            </xsdLocal:LastBillPriceCurrencyCode>
            <xsdLocal:LastBillPrice>
              <xsl:value-of select="xsdLocal1:RCRMLastBillPrice"/>
            </xsdLocal:LastBillPrice>
            <xsdLocal:InitialTerm>
              <xsl:value-of select="xsdLocal1:RCRMInitialTerm"/>
            </xsdLocal:InitialTerm>
            <xsdLocal:InflightQuoteOrderCalc>
              <xsl:value-of select="xsdLocal1:RCRMInflightQuoteOrderCalc"/>
            </xsdLocal:InflightQuoteOrderCalc>
            <xsdLocal:FreeTrialFlag>
              <xsl:value-of select="xsdLocal1:RCRMFreeTrialFlag"/>
            </xsdLocal:FreeTrialFlag>
            <xsdLocal:FreeTrialEndDate>
              <xsl:value-of select="xsdLocal1:RCRMFreeTrialEndDate"/>
            </xsdLocal:FreeTrialEndDate>
            <xsdLocal:FixedTermEndDate>
              <xsl:value-of select="xsdLocal1:RCRMFixedTermEndDate"/>
            </xsdLocal:FixedTermEndDate>
            <xsdLocal:ContractNumber>
              <xsl:value-of select="xsdLocal1:RCRMContractNumber"/>
            </xsdLocal:ContractNumber>
            <xsdLocal:ContactUserId>
              <xsl:value-of select="xsdLocal1:RCRMContactUserId"/>
            </xsdLocal:ContactUserId>
            <xsdLocal:ContactUUID>
              <xsl:value-of select="xsdLocal1:RCRMContactUUID"/>
            </xsdLocal:ContactUUID>
            <xsdLocal:ClientRenewByDate>
              <xsl:value-of select="xsdLocal1:RCRMClientRenewByDate"/>
            </xsdLocal:ClientRenewByDate>
            <xsdLocal:BillingAccountSite>
              <xsl:value-of select="xsdLocal1:RCRMBillingAccountSite"/>
            </xsdLocal:BillingAccountSite>
            <xsdLocal:BillingAccountNum>
              <xsl:value-of select="xsdLocal1:RCRMBillingAccountNum"/>
            </xsdLocal:BillingAccountNum>
            <xsdLocal:AssetSoldToAccountNum>
              <xsl:value-of select="xsdLocal1:RCRMAssetSoldToAccountNum"/>
            </xsdLocal:AssetSoldToAccountNum>
            <xsdLocal:AssetLocationAccount>
              <xsl:value-of select="xsdLocal1:RCRMAssetLocationAccount"/>
            </xsdLocal:AssetLocationAccount>
            <xsdLocal:AssetInstallAccountNum>
              <xsl:value-of select="xsdLocal1:RCRMAssetInstallAccountNum"/>
            </xsdLocal:AssetInstallAccountNum>
            <xsdLocal:ProductPartNumber>
              <xsl:value-of select="xsdLocal1:ProductPartNumber"/>
            </xsdLocal:ProductPartNumber>
            <xsdLocal:ProductName>
              <xsl:value-of select="xsdLocal1:ProductName"/>
            </xsdLocal:ProductName>
            <xsdLocal:ProductId>
              <xsl:value-of select="xsdLocal1:ProductId"/>
            </xsdLocal:ProductId>
            <xsdLocal:ParentAssetId>
              <xsl:value-of select="xsdLocal1:ParentAssetId"/>
            </xsdLocal:ParentAssetId>
            <xsdLocal:OwnerLastName>
              <xsl:value-of select="xsdLocal1:OwnerLastName"/>
            </xsdLocal:OwnerLastName>
            <xsdLocal:OwnerFirstName>
              <xsl:value-of select="xsdLocal1:OwnerFirstName"/>
            </xsdLocal:OwnerFirstName>
            <xsdLocal:OwnerContactId>
              <xsl:value-of select="xsdLocal1:OwnerContactId"/>
            </xsdLocal:OwnerContactId>
            <xsdLocal:NetPrice>
              <xsl:value-of select="xsdLocal1:NetPrice"/>
            </xsdLocal:NetPrice>
            <xsdLocal:IntegrationId>
              <xsl:value-of select="xsdLocal1:IntegrationId"/>
            </xsdLocal:IntegrationId>
            <xsdLocal:InstallDate>
              <xsl:value-of select="xsdLocal1:InstallDate"/>
            </xsdLocal:InstallDate>
            <xsdLocal:Id>
              <xsl:value-of select="xsdLocal1:Id"/>
            </xsdLocal:Id>
            <xsdLocal:EmailAddress>
              <xsl:value-of select="xsdLocal1:EmailAddress"/>
            </xsdLocal:EmailAddress>
            <xsdLocal:EffectiveEndDate>
              <xsl:value-of select="xsdLocal1:EffectiveEndDate"/>
            </xsdLocal:EffectiveEndDate>
            <xsdLocal:AssetNumber>
              <xsl:value-of select="xsdLocal1:AssetNumber"/>
            </xsdLocal:AssetNumber>
            <xsdLocal:ActionCode>
              <xsl:value-of select="xsdLocal1:ActionCode"/>
            </xsdLocal:ActionCode>
            <xsl:for-each select="xsdLocal1:Attributes">
              <xsdLocal:Attributes>
                <xsdLocal:TextValue>
                  <xsl:value-of select="xsdLocal1:TextValue"/>
                </xsdLocal:TextValue>
                <xsdLocal:ProductId>
                  <xsl:value-of select="xsdLocal1:ProductId"/>
                </xsdLocal:ProductId>
                <xsdLocal:ObjectId>
                  <xsl:value-of select="xsdLocal1:ObjectId"/>
                </xsdLocal:ObjectId>
                <xsdLocal:Name>
                  <xsl:value-of select="xsdLocal1:Name"/>
                </xsdLocal:Name>
                <xsdLocal:ConfigurationModelId>
                  <xsl:value-of select="xsdLocal1:ConfigurationModelId"/>
                </xsdLocal:ConfigurationModelId>
              </xsdLocal:Attributes>
            </xsl:for-each>
          </xsdLocal:Assets>
        </xsl:for-each>
      </xsdLocal:ListOfAssetDetails>
    </xsdLocal:assetDataResponseElement>
  </xsl:template>
</xsl:stylesheet>
