<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/EAIMetaData/schemas/EAI.MSG.CM.197_ContactEvent.xsd"/>
      <rootElement name="contactEvent" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CM/ContactPublish"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="EAI.MSG.CM.288_CreateContactRequest.xsd"/>
      <rootElement name="Contacts" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/SAP/ContactSyncRequest"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU JAN 13 17:11:41 IST 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:gcap-cut="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/CM/ContactPublish" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:gcap-NAT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableAccountTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:local="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/SAP/ContactSyncRequest" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:gcap-cat="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" exclude-result-prefixes="xsl gcap-cmt gcap-cut ns0 xsd gcap-NAT ns1 gcap-cat local bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <local:Contacts>
      <local:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="concat(&quot;I065_&quot;,/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:tracingId)"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/ns0:contactEvent/ns0:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </local:eaiHeader>
      <local:actioncode>
        <xsl:value-of select="/ns0:contactEvent/ns0:actionCode"/>
      </local:actioncode>
      <local:contact>
        <local:ContactRowId>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:ContactRowId"/>
        </local:ContactRowId>
        <local:fName>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:firstName"/>
        </local:fName>
        <local:lName>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:lastName"/>
        </local:lName>
        <local:title>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:MM"/>
        </local:title>
        <local:workPhone>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:telNumber"/>
        </local:workPhone>
        <local:mobilePhone>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:CellularPhone"/>
        </local:mobilePhone>
        <local:email>
          <xsl:value-of select="/ns0:contactEvent/ns0:contact/ns0:emailAddress"/>
        </local:email>
        <xsl:for-each select="/ns0:contactEvent/ns0:contact/ns0:ContactAccount">
          <xsl:variable name="row" select="position()"/>
          <xsl:for-each select="../ns0:Function">
            <xsl:choose>
              <xsl:when test="(ns0:RCRMAccountNumber = ../ns0:ContactAccount[$row]/ns0:RCRMAccountNumber) and (../ns0:ContactAccount[$row]/ns0:RCRMSAPPublishedFlag = &quot;Y&quot;) and (dvm:lookupValue(&quot;oramds:/apps/EAIMetaData/dvm/SAPCMFunctionFilterMap.dvm&quot;,&quot;JOB_FUNCTION&quot;,ns0:Name,&quot;SEND_TO_SAP&quot;,&quot;NO&quot;) = &quot;YES&quot;)">
                <local:Function>
                  <local:Name>
                    <xsl:value-of select="ns0:Name"/>
                  </local:Name>
                  <local:AccountId>
                    <xsl:value-of select="ns0:AccountId"/>
                  </local:AccountId>
                  <local:RCRMAccountNumber>
                    <xsl:value-of select="ns0:RCRMAccountNumber"/>
                  </local:RCRMAccountNumber>
                </local:Function>
              </xsl:when>
            </xsl:choose>
          </xsl:for-each>
        </xsl:for-each>
      </local:contact>
      <local:localFirstName>
        <xsl:value-of select="substring(/ns0:contactEvent/ns0:contact/ns0:localFirstName,1.0,40.0)"/>
      </local:localFirstName>
      <local:localLastName>
        <xsl:value-of select="substring(/ns0:contactEvent/ns0:contact/ns0:localLastName,1.0,40.0)"/>
      </local:localLastName>
      <local:localSalutation>
        <xsl:value-of select="substring(/ns0:contactEvent/ns0:contact/ns0:RCRMLocalSalutation,1.0,30.0)"/>
      </local:localSalutation>
    </local:Contacts>
  </xsl:template>
</xsl:stylesheet>
