<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="CSZ_PopulateSolutionRS.wsdl"/>
      <rootElement name="EAICSZPopulateSolution" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/PopulateSolution"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="EAI.SRV.CCRM.045_PopulateSolutionService.wsdl"/>
      <rootElement name="RCRM_spcKNOVA_spcActivity_Input" namespace="http://www.reuters.com/2008/07/14/GCAP/RCRM"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [MON JUL 21 11:59:59 BST 2008]. -->
?>
<xsl:stylesheet version="1.0" xmlns:inp1="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CSZ/PopulateSolution" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.reuters.com/2008/07/14/GCAP/RCRM" xmlns:xsdLocal1="http://www.siebel.com/xml/RCRM%20Service%20Request" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/CommonServiceRequestTypes" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns3="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:ns0="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/CSZ" exclude-result-prefixes="xsl inp1 ns1 xsd ns2 ns3 ns0 tns xsdLocal1 soap soapenc bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <tns:RCRM_spcKNOVA_spcActivity_Input>
      <xsdLocal1:RcrmServiceRequestNoBrs>
        <xsdLocal1:ContactLastName>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:ContactLastName"/>
        </xsdLocal1:ContactLastName>
        <xsdLocal1:ContactFirstName>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:ContactFirstName"/>
        </xsdLocal1:ContactFirstName>
        <xsdLocal1:ContactEmailAddress>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:ContactEmail"/>
        </xsdLocal1:ContactEmailAddress>
        <xsdLocal1:Status>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Status"/>
        </xsdLocal1:Status>
        <xsdLocal1:Account>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Account"/>
        </xsdLocal1:Account>
        <xsdLocal1:Timestamp>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:eaiHeader/ns1:timeStamp"/>
        </xsdLocal1:Timestamp>
        <xsdLocal1:MessageId>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:eaiHeader/ns1:messageId"/>
        </xsdLocal1:MessageId>
        <xsdLocal1:MessageHistory>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:eaiHeader/ns1:messageHistory"/>
        </xsdLocal1:MessageHistory>
        <xsdLocal1:Abstract>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Abstract"/>
        </xsdLocal1:Abstract>
        <xsdLocal1:Area>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:SRType"/>
        </xsdLocal1:Area>
        <xsdLocal1:Description>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Description"/>
        </xsdLocal1:Description>
        <xsdLocal1:Product>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Product"/>
        </xsdLocal1:Product>
        <xsdLocal1:RCRMComponentProduct>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Component"/>
        </xsdLocal1:RCRMComponentProduct>
        <xsdLocal1:RCRMDeliveryInfrastructure>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:DeliveryInfrastructure"/>
        </xsdLocal1:RCRMDeliveryInfrastructure>
        <xsdLocal1:RCRMMarketSector>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:MarketSector"/>
        </xsdLocal1:RCRMMarketSector>
        <xsdLocal1:RCRMProductVersion>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:ProductVersion"/>
        </xsdLocal1:RCRMProductVersion>
        <xsdLocal1:RCRMResolutionText>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:Resolution"/>
        </xsdLocal1:RCRMResolutionText>
        <xsdLocal1:SRNumber>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:SRNumber"/>
        </xsdLocal1:SRNumber>
        <xsdLocal1:Sub-Area>
          <xsl:value-of select="/inp1:EAICSZPopulateSolution/inp1:SRDetails/inp1:SRSubType"/>
        </xsdLocal1:Sub-Area>
      </xsdLocal1:RcrmServiceRequestNoBrs>
    </tns:RCRM_spcKNOVA_spcActivity_Input>
  </xsl:template>
</xsl:stylesheet>
