<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="EAI.SRV.EXT.CM.311_ContactPublishStatusGenericService.wsdl"/>
      <rootElement name="ContactPublishStatus" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/external/GenericContactStatus"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://inkaban3ua-eai01:7777/orabpel/ccrmasync/CCRMCM_PropagateContactErrorStatus/CCRMCM_PropagateContactErrorStatus?wsdl"/>
      <rootElement name="PublishContactRequestReponse" namespace="http://www.siebel.com/xml/RCRMContactPublish"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU SEP 15 03:14:22 GMT+05:30 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:tns="http://www.reuters.com/ns/2007/09/01/GCAP/external/GenericContactStatus" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://www.siebel.com/xml/RCRMContactPublish" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:ns0="http://xmlns.oracle.com/CCRMCM_PropagateContactErrorStatus" exclude-result-prefixes="xsl mime wsdl tns http xsd soap soapenc tm plnk wsa ns1 ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns1:PublishContactRequestReponse>
      <ns1:Header>
        <ns1:messageHistory>
          <xsl:value-of select="/tns:ContactPublishStatus/tns:system"/>
        </ns1:messageHistory>
        <ns1:tracingId>
          <xsl:value-of select="/tns:ContactPublishStatus/tns:trace_id"/>
        </ns1:tracingId>
      </ns1:Header>
      <ns1:PublishContactRequest>
        <ns1:Contact>
          <ns1:ContactRowId>
            <xsl:value-of select="/tns:ContactPublishStatus/tns:row_id"/>
          </ns1:ContactRowId>
        </ns1:Contact>
      </ns1:PublishContactRequest>
      <ns1:PublishContactResponse>
        <ns1:Response>
          <xsl:value-of select="/tns:ContactPublishStatus/tns:message_type"/>
        </ns1:Response>
        <ns1:ResponseMessage>
          <xsl:value-of select="/tns:ContactPublishStatus/tns:message"/>
        </ns1:ResponseMessage>
      </ns1:PublishContactResponse>
    </ns1:PublishContactRequestReponse>
  </xsl:template>
</xsl:stylesheet>
