<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:Port_0="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:this="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices/PA"
	name="Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttp_Service"
	targetNamespace="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices/PA">
	<wsdl:import location="EAI.SRV.EXT.002_PropagateUserService.wsdl"
		namespace="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices" />
	<wsdl:binding
		name="Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttpBinding"
		type="Port_0:PropagateUserInterface">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="propagateUser">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service
		name="Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttpService">
		<wsdl:port
			binding="this:Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttpBinding"
			name="Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttpPort">
                        <soap:address location="${cpfg.protocol}://${cpfg.host}/MM_GCAPInboundWeb/sca/Exp_PropagateUserInterface_${cpfg.domain}"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
