<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Exp_PropagateUserInterface_PA_PropagateUserInterfaceHttp_Service"
     targetNamespace="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices/PA"
     xmlns:ns1="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices/PA"
     xmlns:ns="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="PropagateUserInterface_PL">
        <plnk:role name="PropagateUserInterface_Role">
            <plnk:portType name="ns:PropagateUserInterface"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.reuters.com/ns/2008/05/16/AAA/ESB/SBO/GCAP/UserManagementServices/PA"
         location="MM_GCAPInbound_Exp_PropagateUserInterface_PA.wsdl"/>
</wsdl:definitions>
