<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://inkaban3ua-eai01:7777/orabpel/ccrmasync/CCRMOM_OrderRequestValidatorStub/EAI.MSG.CCRM.OM.138_OrderRequest.xsd"/>
      <rootElement name="orderRequest" namespace="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="AssetCacheDBAdapter_table.xsd"/>
      <rootElement name="AssetCacheCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/AssetCacheDBAdapter"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [THU AUG 12 15:26:08 GMT+05:30 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns3="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:comt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonOrderTypes" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsdLocal="http://www.reuters.com/ns/2007/01/25/GCAP/EAI/CCRM/OM/OrderManagement" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:ns2="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/AssetCacheDBAdapter" exclude-result-prefixes="xsl cmt ns3 xs comt xsdLocal ns1 ns2 ns0 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <ns0:AssetCacheCollection>
      <xsl:for-each select="/xsdLocal:orderRequest/xsdLocal:orderLineItem">
        <xsl:if test="((../xsdLocal:messageHeader/comt:actionCode = &quot;Create&quot;) and (comt:actionCode = &quot;Add&quot;)) or (comt:billingPlatform=&quot;SAP&quot;)">
        <ns0:AssetCache>
            <ns0:assetIntegrationId>
              <xsl:value-of select="comt:assetIntegrationId"/>
            </ns0:assetIntegrationId>
            <xsl:if test="comt:permissioningStatus = &quot;In Progress&quot;">
              <ns0:permissioningSystem>
                <xsl:value-of select="comt:permissioningSystem"/>
              </ns0:permissioningSystem>
            </xsl:if>
            <ns0:pli>
              <xsl:value-of select="comt:PLI"/>
            </ns0:pli>
            <xsl:if test="comt:orderLineStatus = &quot;In Progress&quot; or comt:billingPlatform=&quot;SAP&quot;">
              <ns0:billingplatform>
                <xsl:value-of select="comt:billingPlatform"/>
              </ns0:billingplatform>
            </xsl:if>
          </ns0:AssetCache>
        </xsl:if>
      </xsl:for-each>
    </ns0:AssetCacheCollection>
  </xsl:template>
</xsl:stylesheet>
