<?binding.jca SFDCOP_POLLING_V_db.jca?>
<definitions name="SFDCOP_POLLING_V" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SFDCOP_POLLING_V/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SFDCOP_POLLING_V/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SFDCOPPOLLINGV">
    <plt:partnerLinkType name="SFDCOP_POLLING_V_plt">
        <plt:role name="SFDCOP_POLLING_V_role">
            <plt:portType name="tns:SFDCOP_POLLING_V_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SFDCOPPOLLINGV" schemaLocation="SFDCOPPOLLINGV_table.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/OpportunityManagement" schemaLocation="EAI.MSG.OP.232_OpportunityEvent.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/OpportunityManagement" schemaLocation="ExtendedOpportunityEvent.xsd"/>
        </schema>
    </types>
    <message name="SfdcopPollingVCollection_msg">
        <part name="SfdcopPollingVCollection" element="top:SfdcopPollingVCollection"/>
    </message>
    <portType name="SFDCOP_POLLING_V_ptt">
        <operation name="receive">
            <input message="tns:SfdcopPollingVCollection_msg"/>
        </operation>
    </portType>
</definitions>
