<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="oramds:/apps/EAIMetaData/schemas/EAI.MSG.AM.176_AccountEvent.xsd"/>
      <rootElement name="accountEvent" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/AM/AccountPublish"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/EAIMetaData/schemas/EAI.MSG.AM.176_AccountEvent.xsd"/>
      <rootElement name="accountEvent" namespace="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/AM/AccountPublish"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [TUE JAN 18 14:41:49 GMT+05:30 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:gcap-cmt="http://www.reuters.com/ns/2007/09/01/GCAP/CommonMessageTypes" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:gcap-cut="http://www.reuters.com/ns/2007/09/01/GCAP/CommonUserTypes" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gcap-NUT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableUserTypes" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:gcap-NAT="http://www.reuters.com/ns/2007/09/01/GCAP/NillableAccountTypes" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:local="http://www.reuters.com/ns/2007/09/01/GCAP/EAI/AM/AccountPublish" xmlns:ns0="http://www.reuters.com/ns/2007/09/01/GCAP/SchemaAnnotations" xmlns:gcap-cat="http://www.reuters.com/ns/2007/09/01/GCAP/CommonAccountTypes" exclude-result-prefixes="xsl gcap-cmt gcap-cut xsd gcap-NUT gcap-NAT local ns0 gcap-cat bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <local:accountEvent>
      <local:eaiHeader>
        <gcap-cmt:applicationId>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:applicationId"/>
        </gcap-cmt:applicationId>
        <gcap-cmt:transactionId>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:transactionId"/>
        </gcap-cmt:transactionId>
        <gcap-cmt:messageId>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:messageId"/>
        </gcap-cmt:messageId>
        <gcap-cmt:messageHistory>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:messageHistory"/>
        </gcap-cmt:messageHistory>
        <gcap-cmt:tracingId>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:tracingId"/>
        </gcap-cmt:tracingId>
        <gcap-cmt:timeStamp>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:timeStamp"/>
        </gcap-cmt:timeStamp>
        <gcap-cmt:instanceId>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:instanceId"/>
        </gcap-cmt:instanceId>
        <gcap-cmt:timeToLive>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:timeToLive"/>
        </gcap-cmt:timeToLive>
        <gcap-cmt:payloadVersion>
          <xsl:value-of select="/local:accountEvent/local:eaiHeader/gcap-cmt:payloadVersion"/>
        </gcap-cmt:payloadVersion>
      </local:eaiHeader>
      <local:publishAccountToSAP>
        <xsl:value-of select="/local:accountEvent/local:publishAccountToSAP"/>
      </local:publishAccountToSAP>
      <local:Timestamp>
        <xsl:value-of select="/local:accountEvent/local:Timestamp"/>
      </local:Timestamp>
      <local:actionCode>
        <xsl:value-of select="/local:accountEvent/local:actionCode"/>
      </local:actionCode>
      <local:country>
        <xsl:value-of select="/local:accountEvent/local:country"/>
      </local:country>
      <local:account>
        <local:RCRMFinancialCharges>
          <xsl:value-of select="/local:accountEvent/local:account/local:RCRMFinancialCharges"/>
        </local:RCRMFinancialCharges>
        <local:trscAgreementNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:trscAgreementNumber"/>
        </local:trscAgreementNumber>
        <local:urgentBillingFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:urgentBillingFlag"/>
        </local:urgentBillingFlag>
        <local:softDollarCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:softDollarCode"/>
        </local:softDollarCode>
        <local:SAPPublishedFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:SAPPublishedFlag"/>
        </local:SAPPublishedFlag>
        <local:billingLanguage>
          <xsl:value-of select="/local:accountEvent/local:account/local:billingLanguage"/>
        </local:billingLanguage>
        <local:billingCurrency>
          <xsl:value-of select="/local:accountEvent/local:account/local:billingCurrency"/>
        </local:billingCurrency>
        <local:parentCustomerReferenceNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:parentCustomerReferenceNumber"/>
        </local:parentCustomerReferenceNumber>
        <local:KNOwned>
          <xsl:value-of select="/local:accountEvent/local:account/local:KNOwned"/>
        </local:KNOwned>
        <local:invoiceDeliveryMethod>
          <xsl:value-of select="/local:accountEvent/local:account/local:invoiceDeliveryMethod"/>
        </local:invoiceDeliveryMethod>
        <local:hardcopyDispatchMethod>
          <xsl:value-of select="/local:accountEvent/local:account/local:hardcopyDispatchMethod"/>
        </local:hardcopyDispatchMethod>
        <local:extBillingAccountDesc>
          <xsl:value-of select="/local:accountEvent/local:account/local:extBillingAccountDesc"/>
        </local:extBillingAccountDesc>
        <local:Dummy3>
          <xsl:value-of select="/local:accountEvent/local:account/local:Dummy3"/>
        </local:Dummy3>
        <local:Dummy2>
          <xsl:value-of select="/local:accountEvent/local:account/local:Dummy2"/>
        </local:Dummy2>
        <local:Dummy1>
          <xsl:value-of select="/local:accountEvent/local:account/local:Dummy1"/>
        </local:Dummy1>
        <local:tomIntegrationFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:tomIntegrationFlag"/>
        </local:tomIntegrationFlag>
        <local:CMIntegrationFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:CMIntegrationFlag"/>
        </local:CMIntegrationFlag>
        <local:subRegion>
          <xsl:value-of select="/local:accountEvent/local:account/local:subRegion"/>
        </local:subRegion>
        <local:SuspendBillingFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:SuspendBillingFlag"/>
        </local:SuspendBillingFlag>
        <local:TCId>
          <xsl:value-of select="/local:accountEvent/local:account/local:TCId"/>
        </local:TCId>
        <local:primaryAccountFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountFlag"/>
        </local:primaryAccountFlag>
        <local:PerClientBillingFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:PerClientBillingFlag"/>
        </local:PerClientBillingFlag>
        <local:oaid>
          <xsl:value-of select="/local:accountEvent/local:account/local:oaid"/>
        </local:oaid>
        <local:oaName>
          <xsl:value-of select="/local:accountEvent/local:account/local:oaName"/>
        </local:oaName>
        <local:multiCenterNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:multiCenterNumber"/>
        </local:multiCenterNumber>
        <local:InvoicingCenter>
          <xsl:value-of select="/local:accountEvent/local:account/local:InvoicingCenter"/>
        </local:InvoicingCenter>
        <local:invoiceDescription>
          <xsl:value-of select="/local:accountEvent/local:account/local:invoiceDescription"/>
        </local:invoiceDescription>
        <local:GeoCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:GeoCode"/>
        </local:GeoCode>
        <local:CityCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:CityCode"/>
        </local:CityCode>
        <local:csIntegrationFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:csIntegrationFlag"/>
        </local:csIntegrationFlag>
        <local:alternateSubscriberNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:alternateSubscriberNumber"/>
        </local:alternateSubscriberNumber>
        <local:addressType>
          <xsl:value-of select="/local:accountEvent/local:account/local:addressType"/>
        </local:addressType>
        <local:phoneNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:phoneNumber"/>
        </local:phoneNumber>
        <local:faxNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:faxNumber"/>
        </local:faxNumber>
        <local:id>
          <xsl:value-of select="/local:accountEvent/local:account/local:id"/>
        </local:id>
        <local:irasReference>
          <xsl:value-of select="/local:accountEvent/local:account/local:irasReference"/>
        </local:irasReference>
        <local:accountStatus>
          <xsl:value-of select="/local:accountEvent/local:account/local:accountStatus"/>
        </local:accountStatus>
        <local:contactRelationshipType>
          <xsl:value-of select="/local:accountEvent/local:account/local:contactRelationshipType"/>
        </local:contactRelationshipType>
        <local:currencyCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:currencyCode"/>
        </local:currencyCode>
        <local:description>
          <xsl:value-of select="/local:accountEvent/local:account/local:description"/>
        </local:description>
        <local:groupTypeCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:groupTypeCode"/>
        </local:groupTypeCode>
        <local:masterAccountId>
          <xsl:value-of select="/local:accountEvent/local:account/local:masterAccountId"/>
        </local:masterAccountId>
        <local:name>
          <xsl:value-of select="/local:accountEvent/local:account/local:name"/>
        </local:name>
        <local:orgId>
          <xsl:value-of select="/local:accountEvent/local:account/local:orgId"/>
        </local:orgId>
        <local:parentAccountId>
          <xsl:value-of select="/local:accountEvent/local:account/local:parentAccountId"/>
        </local:parentAccountId>
        <local:partyName>
          <xsl:value-of select="/local:accountEvent/local:account/local:partyName"/>
        </local:partyName>
        <local:partyTypeCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:partyTypeCode"/>
        </local:partyTypeCode>
        <local:partyUId>
          <xsl:value-of select="/local:accountEvent/local:account/local:partyUId"/>
        </local:partyUId>
        <local:primaryAccountCity>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountCity"/>
        </local:primaryAccountCity>
        <local:primaryAccountCountry>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountCountry"/>
        </local:primaryAccountCountry>
        <local:primaryAccountPostalCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountPostalCode"/>
        </local:primaryAccountPostalCode>
        <local:primaryAccountState>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountState"/>
        </local:primaryAccountState>
        <local:primaryAccountStreetAddress>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAccountStreetAddress"/>
        </local:primaryAccountStreetAddress>
        <local:primaryAddressId>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAddressId"/>
        </local:primaryAddressId>
        <local:primaryAddressName>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryAddressName"/>
        </local:primaryAddressName>
        <local:primaryContactId>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryContactId"/>
        </local:primaryContactId>
        <local:primaryPositionId>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryPositionId"/>
        </local:primaryPositionId>
        <local:accountClass>
          <xsl:value-of select="/local:accountEvent/local:account/local:accountClass"/>
        </local:accountClass>
        <local:accountFamily>
          <xsl:value-of select="/local:accountEvent/local:account/local:accountFamily"/>
        </local:accountFamily>
        <local:billingFrequency>
          <xsl:value-of select="/local:accountEvent/local:account/local:billingFrequency"/>
        </local:billingFrequency>
        <local:businessChannel>
          <xsl:value-of select="/local:accountEvent/local:account/local:businessChannel"/>
        </local:businessChannel>
        <local:coreSuiteStatus>
          <xsl:value-of select="/local:accountEvent/local:account/local:coreSuiteStatus"/>
        </local:coreSuiteStatus>
        <local:errorMessage>
          <xsl:value-of select="/local:accountEvent/local:account/local:errorMessage"/>
        </local:errorMessage>
        <local:fieldServiceLocation>
          <xsl:value-of select="/local:accountEvent/local:account/local:fieldServiceLocation"/>
        </local:fieldServiceLocation>
        <local:internalAccountFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:internalAccountFlag"/>
        </local:internalAccountFlag>
        <local:organisationType>
          <xsl:value-of select="/local:accountEvent/local:account/local:organisationType"/>
        </local:organisationType>
        <local:organisationTypeDesc>
          <xsl:value-of select="/local:accountEvent/local:account/local:organisationTypeDesc"/>
        </local:organisationTypeDesc>
        <local:payTerms>
          <xsl:value-of select="/local:accountEvent/local:account/local:payTerms"/>
        </local:payTerms>
        <local:primaryChildId>
          <xsl:value-of select="/local:accountEvent/local:account/local:primaryChildId"/>
        </local:primaryChildId>
        <local:quotronClient>
          <xsl:value-of select="/local:accountEvent/local:account/local:quotronClient"/>
        </local:quotronClient>
        <local:region>
          <xsl:value-of select="/local:accountEvent/local:account/local:region"/>
        </local:region>
        <local:subAccountName>
          <xsl:value-of select="/local:accountEvent/local:account/local:subAccountName"/>
        </local:subAccountName>
        <local:subAccountNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:subAccountNumber"/>
        </local:subAccountNumber>
        <local:subscriberCountry>
          <xsl:value-of select="/local:accountEvent/local:account/local:subscriberCountry"/>
        </local:subscriberCountry>
        <local:subscriberCountryCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:subscriberCountryCode"/>
        </local:subscriberCountryCode>
        <local:subscriberNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:subscriberNumber"/>
        </local:subscriberNumber>
        <local:subscriberShortName>
          <xsl:value-of select="/local:accountEvent/local:account/local:subscriberShortName"/>
        </local:subscriberShortName>
        <local:sysUpdatedBy>
          <xsl:value-of select="/local:accountEvent/local:account/local:sysUpdatedBy"/>
        </local:sysUpdatedBy>
        <local:taxCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:taxCode"/>
        </local:taxCode>
        <local:vatCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:vatCode"/>
        </local:vatCode>
        <local:site>
          <xsl:value-of select="/local:accountEvent/local:account/local:site"/>
        </local:site>
        <local:SFDCID>
          <xsl:value-of select="/local:accountEvent/local:account/local:SFDCID"/>
        </local:SFDCID>
        <local:HomePage>
          <xsl:value-of select="/local:accountEvent/local:account/local:HomePage"/>
        </local:HomePage>
        <local:Segment>
          <xsl:value-of select="/local:accountEvent/local:account/local:Segment"/>
        </local:Segment>
        <local:ownerMail>
          <xsl:value-of select="/local:accountEvent/local:account/local:ownerMail"/>
        </local:ownerMail>
        <local:masterAccountClass>
          <xsl:value-of select="/local:accountEvent/local:account/local:masterAccountClass"/>
        </local:masterAccountClass>
        <local:taxIDNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:taxIDNumber"/>
        </local:taxIDNumber>
        <local:customerReference>
          <xsl:value-of select="/local:accountEvent/local:account/local:customerReference"/>
        </local:customerReference>
        <local:customerJourney>
          <xsl:value-of select="/local:accountEvent/local:account/local:customerJourney"/>
        </local:customerJourney>
        <local:accountNotes>
          <xsl:value-of select="/local:accountEvent/local:account/local:accountNotes"/>
        </local:accountNotes>
        <local:accountDescription>
          <xsl:value-of select="/local:accountEvent/local:account/local:accountDescription"/>
        </local:accountDescription>
        <local:parentAccountClass>
          <xsl:value-of select="/local:accountEvent/local:account/local:parentAccountClass"/>
        </local:parentAccountClass>
        <local:caID>
          <xsl:value-of select="/local:accountEvent/local:account/local:caID"/>
        </local:caID>
        <local:TDOStatus>
          <xsl:value-of select="/local:accountEvent/local:account/local:TDOStatus"/>
        </local:TDOStatus>
        <local:TDOCheckDate>
          <xsl:value-of select="/local:accountEvent/local:account/local:TDOCheckDate"/>
        </local:TDOCheckDate>
        <local:CreditCheckStatus>
          <xsl:value-of select="/local:accountEvent/local:account/local:CreditCheckStatus"/>
        </local:CreditCheckStatus>
        <local:CreditCheckDate>
          <xsl:value-of select="/local:accountEvent/local:account/local:CreditCheckDate"/>
        </local:CreditCheckDate>
        <local:ContractType>
          <xsl:value-of select="/local:accountEvent/local:account/local:ContractType"/>
        </local:ContractType>
        <local:AccountTypeCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:AccountTypeCode"/>
        </local:AccountTypeCode>
        <local:siebelAccountStatus>
          <xsl:value-of select="/local:accountEvent/local:account/local:siebelAccountStatus"/>
        </local:siebelAccountStatus>
        <local:lastUpdated>
          <xsl:value-of select="/local:accountEvent/local:account/local:lastUpdated"/>
        </local:lastUpdated>
        <local:customerReferenceNumber>
          <xsl:value-of select="/local:accountEvent/local:account/local:customerReferenceNumber"/>
        </local:customerReferenceNumber>
        <local:localAccountName>
          <xsl:value-of select="/local:accountEvent/local:account/local:localAccountName"/>
        </local:localAccountName>
        <local:legalEntityFlag>
          <xsl:value-of select="/local:accountEvent/local:account/local:legalEntityFlag"/>
        </local:legalEntityFlag>
        <local:localStreetAddress>
          <xsl:value-of select="/local:accountEvent/local:account/local:localStreetAddress"/>
        </local:localStreetAddress>
        <local:localCity>
          <xsl:value-of select="/local:accountEvent/local:account/local:localCity"/>
        </local:localCity>
        <local:localState>
          <xsl:value-of select="/local:accountEvent/local:account/local:localState"/>
        </local:localState>
        <local:localCountry>
          <xsl:value-of select="/local:accountEvent/local:account/local:localCountry"/>
        </local:localCountry>
        <local:localPostalCode>
          <xsl:value-of select="/local:accountEvent/local:account/local:localPostalCode"/>
        </local:localPostalCode>
        <local:trscFields>
          <local:TRSCversion>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:TRSCversion"/>
          </local:TRSCversion>
          <local:TRSCStartDate>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:TRSCStartDate"/>
          </local:TRSCStartDate>
          <local:TRSCEndDate>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:TRSCEndDate"/>
          </local:TRSCEndDate>
          <local:NonStdPriceAdjClause>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:NonStdPriceAdjClause"/>
          </local:NonStdPriceAdjClause>
          <local:AgreementType>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:AgreementType"/>
          </local:AgreementType>
          <local:AgreementStatus>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:AgreementStatus"/>
          </local:AgreementStatus>
          <local:AgreementNumber>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:AgreementNumber"/>
          </local:AgreementNumber>
          <local:TermStatus>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:TermStatus"/>
          </local:TermStatus>
          <local:TRBPVersion>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:TRBPVersion"/>
          </local:TRBPVersion>
          <local:Dummy3>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Dummy3"/>
          </local:Dummy3>
          <local:Dummy2>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Dummy2"/>
          </local:Dummy2>
          <local:Dummy1>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Dummy1"/>
          </local:Dummy1>
          <local:ContractDetail>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:ContractDetail"/>
          </local:ContractDetail>
          <local:Name>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Name"/>
          </local:Name>
          <local:Id>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Id"/>
          </local:Id>
          <local:Discount>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:Discount"/>
          </local:Discount>
          <local:AgreementId>
            <xsl:value-of select="/local:accountEvent/local:account/local:trscFields/local:AgreementId"/>
          </local:AgreementId>
        </local:trscFields>
        <local:trbcFields>
          <local:industryType>
            <xsl:value-of select="/local:accountEvent/local:account/local:trbcFields/local:industryType"/>
          </local:industryType>
          <local:industrySubType>
            <xsl:value-of select="/local:accountEvent/local:account/local:trbcFields/local:industrySubType"/>
          </local:industrySubType>
        </local:trbcFields>
        <local:customerGroup>
          <xsl:value-of select="/local:accountEvent/local:account/local:customerGroup"/>
        </local:customerGroup>
        <local:LegacyParentId>
          <xsl:value-of select="/local:accountEvent/local:account/local:LegacyParentId"/>
        </local:LegacyParentId>
        <local:localFloorAddress>
          <xsl:value-of select="/local:accountEvent/local:account/local:localFloorAddress"/>
        </local:localFloorAddress>
       </local:account>
      <xsl:for-each select="/local:accountEvent/local:accountAddress">
        <local:accountAddress>
          <local:faxNumber>
            <xsl:value-of select="local:faxNumber"/>
          </local:faxNumber>
          <local:id>
            <xsl:value-of select="local:id"/>
          </local:id>
          <local:accountId>
            <xsl:value-of select="local:accountId"/>
          </local:accountId>
          <local:accountLoc>
            <xsl:value-of select="local:accountLoc"/>
          </local:accountLoc>
          <local:accountName>
            <xsl:value-of select="local:accountName"/>
          </local:accountName>
          <local:accountPrimaryAddressId>
            <xsl:value-of select="local:accountPrimaryAddressId"/>
          </local:accountPrimaryAddressId>
          <local:activeStatus>
            <xsl:value-of select="local:activeStatus"/>
          </local:activeStatus>
          <local:addrDescription>
            <xsl:value-of select="local:addrDescription"/>
          </local:addrDescription>
          <local:addressId>
            <xsl:value-of select="local:addressId"/>
          </local:addressId>
          <local:addressName>
            <xsl:value-of select="local:addressName"/>
          </local:addressName>
          <local:addressType>
            <xsl:value-of select="local:addressType"/>
          </local:addressType>
          <local:apartmentNumber>
            <xsl:value-of select="local:apartmentNumber"/>
          </local:apartmentNumber>
          <local:billAddressFlag>
            <xsl:value-of select="local:billAddressFlag"/>
          </local:billAddressFlag>
          <local:city>
            <xsl:value-of select="local:city"/>
          </local:city>
          <local:contactId>
            <xsl:value-of select="local:contactId"/>
          </local:contactId>
          <local:country>
            <xsl:value-of select="local:country"/>
          </local:country>
          <local:county>
            <xsl:value-of select="local:county"/>
          </local:county>
          <local:descriptor>
            <xsl:value-of select="local:descriptor"/>
          </local:descriptor>
          <local:emailAddress>
            <xsl:value-of select="local:emailAddress"/>
          </local:emailAddress>
          <local:integrationId>
            <xsl:value-of select="local:integrationId"/>
          </local:integrationId>
          <local:landlordName>
            <xsl:value-of select="local:landlordName"/>
          </local:landlordName>
          <local:landlordPhoneNumber>
            <xsl:value-of select="local:landlordPhoneNumber"/>
          </local:landlordPhoneNumber>
          <local:lastUpdatedConAddr>
            <xsl:value-of select="local:lastUpdatedConAddr"/>
          </local:lastUpdatedConAddr>
          <local:localOperatingCompany>
            <xsl:value-of select="local:localOperatingCompany"/>
          </local:localOperatingCompany>
          <local:localOperatingCompanyId>
            <xsl:value-of select="local:localOperatingCompanyId"/>
          </local:localOperatingCompanyId>
          <local:localOperatingCompanySite>
            <xsl:value-of select="local:localOperatingCompanySite"/>
          </local:localOperatingCompanySite>
          <local:mainAddressFlag>
            <xsl:value-of select="local:mainAddressFlag"/>
          </local:mainAddressFlag>
          <local:parentAddress>
            <xsl:value-of select="local:parentAddress"/>
          </local:parentAddress>
          <local:parentAddressId>
            <xsl:value-of select="local:parentAddressId"/>
          </local:parentAddressId>
          <local:phoneNumber>
            <xsl:value-of select="local:phoneNumber"/>
          </local:phoneNumber>
          <local:postalCode>
            <xsl:value-of select="local:postalCode"/>
          </local:postalCode>
          <local:province>
            <xsl:value-of select="local:province"/>
          </local:province>
          <local:rcrmaddressType>
            <xsl:value-of select="local:rcrmaddressType"/>
          </local:rcrmaddressType>
          <local:csaddressType>
            <xsl:value-of select="local:csaddressType"/>
          </local:csaddressType>
          <local:streetAddress>
            <xsl:value-of select="local:streetAddress"/>
          </local:streetAddress>
          <local:streetAddress2>
            <xsl:value-of select="local:streetAddress2"/>
          </local:streetAddress2>
          <local:rcrmemailAddress>
            <xsl:value-of select="local:rcrmemailAddress"/>
          </local:rcrmemailAddress>
          <local:floorAddress>
            <xsl:value-of select="local:floorAddress"/>
          </local:floorAddress>
          <local:legacyAddressRef>
            <xsl:value-of select="local:legacyAddressRef"/>
          </local:legacyAddressRef>
          <local:legacyFlag>
            <xsl:value-of select="local:legacyFlag"/>
          </local:legacyFlag>
          <local:localStreet>
            <xsl:value-of select="local:localStreet"/>
          </local:localStreet>
          <local:localCity>
            <xsl:value-of select="local:localCity"/>
          </local:localCity>
          <local:localCountry>
            <xsl:value-of select="local:localCountry"/>
          </local:localCountry>
          <local:localPostalCode>
            <xsl:value-of select="local:localPostalCode"/>
          </local:localPostalCode>
          <local:localState>
            <xsl:value-of select="local:localState"/>
          </local:localState>
          <local:region>
            <xsl:value-of select="local:region"/>
          </local:region>
          <local:rowId>
            <xsl:value-of select="local:rowId"/>
          </local:rowId>
          <local:sInstance>
            <xsl:value-of select="local:sInstance"/>
          </local:sInstance>
          <local:sInstanceId>
            <xsl:value-of select="local:sInstanceId"/>
          </local:sInstanceId>
          <local:skeyId>
            <xsl:value-of select="local:skeyId"/>
          </local:skeyId>
          <local:state>
            <xsl:value-of select="local:state"/>
          </local:state>
          <local:subRegion>
            <xsl:value-of select="local:subRegion"/>
          </local:subRegion>
          <local:type>
            <xsl:value-of select="local:type"/>
          </local:type>
          <local:verifiedFlag>
            <xsl:value-of select="local:verifiedFlag"/>
          </local:verifiedFlag>
        </local:accountAddress>
      </xsl:for-each>
      <xsl:for-each select="/local:accountEvent/local:employee">
        <local:employee>
          <local:publishContactToSAP>
            <xsl:value-of select="local:publishContactToSAP"/>
          </local:publishContactToSAP>
          <local:positionType>
            <xsl:value-of select="local:positionType"/>
          </local:positionType>
          <local:contactWorkNumber>
            <xsl:value-of select="local:contactWorkNumber"/>
          </local:contactWorkNumber>
          <local:contactState>
            <xsl:value-of select="local:contactState"/>
          </local:contactState>
          <local:contactPostalCode>
            <xsl:value-of select="local:contactPostalCode"/>
          </local:contactPostalCode>
          <local:contactFaxNumber>
            <xsl:value-of select="local:contactFaxNumber"/>
          </local:contactFaxNumber>
          <local:contactCountry>
            <xsl:value-of select="local:contactCountry"/>
          </local:contactCountry>
          <local:contactCity>
            <xsl:value-of select="local:contactCity"/>
          </local:contactCity>
          <local:contactAddress>
            <xsl:value-of select="local:contactAddress"/>
          </local:contactAddress>
          <local:contactAccountNumber>
            <xsl:value-of select="local:contactAccountNumber"/>
          </local:contactAccountNumber>
          <local:Dummy1>
            <xsl:value-of select="local:Dummy1"/>
          </local:Dummy1>
          <local:id>
            <xsl:value-of select="local:id"/>
          </local:id>
          <local:modId>
            <xsl:value-of select="local:modId"/>
          </local:modId>
          <local:accountId>
            <xsl:value-of select="local:accountId"/>
          </local:accountId>
          <local:accountLocation>
            <xsl:value-of select="local:accountLocation"/>
          </local:accountLocation>
          <local:accountName2>
            <xsl:value-of select="local:accountName2"/>
          </local:accountName2>
          <local:accountPositionId>
            <xsl:value-of select="local:accountPositionId"/>
          </local:accountPositionId>
          <local:accountRowStatus>
            <xsl:value-of select="local:accountRowStatus"/>
          </local:accountRowStatus>
          <local:accountTeamRole>
            <xsl:value-of select="local:accountTeamRole"/>
          </local:accountTeamRole>
          <local:activeEmail>
            <xsl:value-of select="local:activeEmail"/>
          </local:activeEmail>
          <local:activeFax>
            <xsl:value-of select="local:activeFax"/>
          </local:activeFax>
          <local:activeFirstName>
            <xsl:value-of select="local:activeFirstName"/>
          </local:activeFirstName>
          <local:activeJobTitle>
            <xsl:value-of select="local:activeJobTitle"/>
          </local:activeJobTitle>
          <local:activeLastName>
            <xsl:value-of select="local:activeLastName"/>
          </local:activeLastName>
          <local:activeLoginId>
            <xsl:value-of select="local:activeLoginId"/>
          </local:activeLoginId>
          <local:activeLoginName>
            <xsl:value-of select="local:activeLoginName"/>
          </local:activeLoginName>
          <local:activeMM>
            <xsl:value-of select="local:activeMM"/>
          </local:activeMM>
          <local:activePagerNumber>
            <xsl:value-of select="local:activePagerNumber"/>
          </local:activePagerNumber>
          <local:activePagerPIN>
            <xsl:value-of select="local:activePagerPIN"/>
          </local:activePagerPIN>
          <local:activePhone>
            <xsl:value-of select="local:activePhone"/>
          </local:activePhone>
          <local:contactFirstName>
            <xsl:value-of select="local:contactFirstName"/>
          </local:contactFirstName>
          <local:contactLastName>
            <xsl:value-of select="local:contactLastName"/>
          </local:contactLastName>
          <local:contactPrimaryAddressId>
            <xsl:value-of select="local:contactPrimaryAddressId"/>
          </local:contactPrimaryAddressId>
          <local:contactPrimaryPositionId>
            <xsl:value-of select="local:contactPrimaryPositionId"/>
          </local:contactPrimaryPositionId>
          <local:contactPriorityFlag>
            <xsl:value-of select="local:contactPriorityFlag"/>
          </local:contactPriorityFlag>
          <local:contactRowStatus>
            <xsl:value-of select="local:contactRowStatus"/>
          </local:contactRowStatus>
          <local:costAllocation>
            <xsl:value-of select="local:costAllocation"/>
          </local:costAllocation>
          <local:coverageRole>
            <xsl:value-of select="local:coverageRole"/>
          </local:coverageRole>
          <local:description>
            <xsl:value-of select="local:description"/>
          </local:description>
          <local:division>
            <xsl:value-of select="local:division"/>
          </local:division>
          <local:employeeId>
            <xsl:value-of select="local:employeeId"/>
          </local:employeeId>
          <local:employmentStatus>
            <xsl:value-of select="local:employmentStatus"/>
          </local:employmentStatus>
          <local:groupTypeCode2>
            <xsl:value-of select="local:groupTypeCode2"/>
          </local:groupTypeCode2>
          <local:integrationId>
            <xsl:value-of select="local:integrationId"/>
          </local:integrationId>
          <local:loginId>
            <xsl:value-of select="local:loginId"/>
          </local:loginId>
          <local:middleName>
            <xsl:value-of select="local:middleName"/>
          </local:middleName>
          <local:name2>
            <xsl:value-of select="local:name2"/>
          </local:name2>
          <local:opportunitySalesTeamRole>
            <xsl:value-of select="local:opportunitySalesTeamRole"/>
          </local:opportunitySalesTeamRole>
          <local:parentPositionId>
            <xsl:value-of select="local:parentPositionId"/>
          </local:parentPositionId>
          <local:parentPositionName>
            <xsl:value-of select="local:parentPositionName"/>
          </local:parentPositionName>
          <local:parentPrimaryPositionId>
            <xsl:value-of select="local:parentPrimaryPositionId"/>
          </local:parentPrimaryPositionId>
          <local:partyTypeCode2>
            <xsl:value-of select="local:partyTypeCode2"/>
          </local:partyTypeCode2>
          <local:partyUId2>
            <xsl:value-of select="local:partyUId2"/>
          </local:partyUId2>
          <local:onceOffRevenue>
            <xsl:value-of select="local:onceOffRevenue"/>
          </local:onceOffRevenue>
          <local:responsiblity>
            <xsl:value-of select="local:responsiblity"/>
          </local:responsiblity>
          <local:relationship>
            <xsl:value-of select="local:relationship"/>
          </local:relationship>
          <local:role>
            <xsl:value-of select="local:role"/>
          </local:role>
          <local:rowId>
            <xsl:value-of select="local:rowId"/>
          </local:rowId>
        </local:employee>
      </xsl:for-each>
      <xsl:for-each select="/local:accountEvent/local:contact">
        <local:contact>
          <local:Title>
            <xsl:value-of select="local:Title"/>
          </local:Title>
          <local:SFDCId>
            <xsl:value-of select="local:SFDCId"/>
          </local:SFDCId>
          <local:PrimaryFunction>
            <xsl:value-of select="local:PrimaryFunction"/>
          </local:PrimaryFunction>
          <local:LocalTitle>
            <xsl:value-of select="local:LocalTitle"/>
          </local:LocalTitle>
          <local:LocalStreet>
            <xsl:value-of select="local:LocalStreet"/>
          </local:LocalStreet>
          <local:LocalState>
            <xsl:value-of select="local:LocalState"/>
          </local:LocalState>
          <local:LocalPostcode>
            <xsl:value-of select="local:LocalPostcode"/>
          </local:LocalPostcode>
          <local:LocalLastName>
            <xsl:value-of select="local:LocalLastName"/>
          </local:LocalLastName>
          <local:LocalFirstName>
            <xsl:value-of select="local:LocalFirstName"/>
          </local:LocalFirstName>
          <local:LocalCountry>
            <xsl:value-of select="local:LocalCountry"/>
          </local:LocalCountry>
          <local:LocalCity>
            <xsl:value-of select="local:LocalCity"/>
          </local:LocalCity>
          <local:EndUserActivity>
            <xsl:value-of select="local:EndUserActivity"/>
          </local:EndUserActivity>
          <local:ContactCategory>
            <xsl:value-of select="local:ContactCategory"/>
          </local:ContactCategory>
          <local:AssetFocus1>
            <xsl:value-of select="local:AssetFocus1"/>
          </local:AssetFocus1>
          <local:AccountSFDCId>
            <xsl:value-of select="local:AccountSFDCId"/>
          </local:AccountSFDCId>
          <local:id>
            <xsl:value-of select="local:id"/>
          </local:id>
          <local:accountId>
            <xsl:value-of select="local:accountId"/>
          </local:accountId>
          <local:cellularPhone>
            <xsl:value-of select="local:cellularPhone"/>
          </local:cellularPhone>
          <local:emailAddress2>
            <xsl:value-of select="local:emailAddress2"/>
          </local:emailAddress2>
          <local:employeeFlag>
            <xsl:value-of select="local:employeeFlag"/>
          </local:employeeFlag>
          <local:firstName>
            <xsl:value-of select="local:firstName"/>
          </local:firstName>
          <local:jobTitle>
            <xsl:value-of select="local:jobTitle"/>
          </local:jobTitle>
          <local:lastName>
            <xsl:value-of select="local:lastName"/>
          </local:lastName>
          <local:mm>
            <xsl:value-of select="local:mm"/>
          </local:mm>
          <local:masterAccountId>
            <xsl:value-of select="local:masterAccountId"/>
          </local:masterAccountId>
          <local:partyTypeCD>
            <xsl:value-of select="local:partyTypeCD"/>
          </local:partyTypeCD>
          <local:partyUID3>
            <xsl:value-of select="local:partyUID3"/>
          </local:partyUID3>
          <local:personUId>
            <xsl:value-of select="local:personUId"/>
          </local:personUId>
          <local:primaryPositionId>
            <xsl:value-of select="local:primaryPositionId"/>
          </local:primaryPositionId>
          <local:contactSubType>
            <xsl:value-of select="local:contactSubType"/>
          </local:contactSubType>
          <local:coreSuiteStatus>
            <xsl:value-of select="local:coreSuiteStatus"/>
          </local:coreSuiteStatus>
          <local:directMarketing>
            <xsl:value-of select="local:directMarketing"/>
          </local:directMarketing>
          <local:errorMessage>
            <xsl:value-of select="local:errorMessage"/>
          </local:errorMessage>
          <local:functionId>
            <xsl:value-of select="local:functionId"/>
          </local:functionId>
          <local:PreferredLanguage>
            <xsl:value-of select="local:PreferredLanguage"/>
          </local:PreferredLanguage>
          <local:status>
            <xsl:value-of select="local:status"/>
          </local:status>
          <local:relationshipType>
            <xsl:value-of select="local:relationshipType"/>
          </local:relationshipType>
          <local:workPhone>
            <xsl:value-of select="local:workPhone"/>
          </local:workPhone>
        </local:contact>
      </xsl:for-each>
      <xsl:for-each select="/local:accountEvent/local:attributeValuePair">
        <local:attributeValuePair>
          <local:AccountId>
            <xsl:value-of select="local:AccountId"/>
          </local:AccountId>
          <local:AttributeName>
            <xsl:value-of select="local:AttributeName"/>
          </local:AttributeName>
          <local:AttributeValue>
            <xsl:value-of select="local:AttributeValue"/>
          </local:AttributeValue>
        </local:attributeValuePair>
      </xsl:for-each>
    </local:accountEvent>
  </xsl:template>
</xsl:stylesheet>
